return {
  ["folke/tokyonight.nvim"] = {
    handle = "folke/tokyonight.nvim",
    url = "https://github.com/folke/tokyonight.nvim",
    github_stars = 6700,
    last_git_commit = "2025-01-29",
    priority = 100,
    source = "asm",
    git_path = "folke-tokyonight.nvim",
    git_branch = nil,
    color_names = {
      "tokyonight",
      "tokyonight-day",
      "tokyonight-moon",
      "tokyonight-night",
      "tokyonight-storm",
    },
  },
  ["catppuccin/nvim"] = {
    handle = "catppuccin/nvim",
    url = "https://github.com/catppuccin/nvim",
    github_stars = 5900,
    last_git_commit = "2025-01-30",
    priority = 100,
    source = "asm",
    git_path = "catppuccin-nvim",
    git_branch = nil,
    color_names = {
      "catppuccin",
      "catppuccin-frappe",
      "catppuccin-latte",
      "catppuccin-macchiato",
      "catppuccin-mocha",
    },
  },
  ["rebelot/kanagawa.nvim"] = {
    handle = "rebelot/kanagawa.nvim",
    url = "https://github.com/rebelot/kanagawa.nvim",
    github_stars = 4600,
    last_git_commit = "2025-01-07",
    priority = 100,
    source = "asm",
    git_path = "rebelot-kanagawa.nvim",
    git_branch = nil,
    color_names = {
      "kanagawa",
      "kanagawa-dragon",
      "kanagawa-lotus",
      "kanagawa-wave",
    },
  },
  ["edeneast/nightfox.nvim"] = {
    handle = "edeneast/nightfox.nvim",
    url = "https://github.com/edeneast/nightfox.nvim",
    github_stars = 3300,
    last_git_commit = "2024-12-29",
    priority = 100,
    source = "asm",
    git_path = "edeneast-nightfox.nvim",
    git_branch = nil,
    color_names = {
      "carbonfox",
      "dawnfox",
      "dayfox",
      "duskfox",
      "nightfox",
      "nordfox",
      "terafox",
    },
  },
  ["sainnhe/everforest"] = {
    handle = "sainnhe/everforest",
    url = "https://github.com/sainnhe/everforest",
    github_stars = 3100,
    last_git_commit = "2025-01-16",
    priority = 100,
    source = "asm",
    git_path = "sainnhe-everforest",
    git_branch = nil,
    color_names = {
      "everforest",
    },
  },
  ["nlknguyen/papercolor-theme"] = {
    handle = "nlknguyen/papercolor-theme",
    url = "https://github.com/nlknguyen/papercolor-theme",
    github_stars = 2750,
    last_git_commit = "2024-03-12",
    priority = 0,
    source = "vsc",
    git_path = "nlknguyen-papercolor-theme",
    git_branch = nil,
    color_names = {
      "PaperColor",
    },
  },
  ["rose-pine/neovim"] = {
    handle = "rose-pine/neovim",
    url = "https://github.com/rose-pine/neovim",
    github_stars = 2400,
    last_git_commit = "2025-02-02",
    priority = 100,
    source = "asm",
    git_path = "rose-pine-neovim",
    git_branch = nil,
    color_names = {
      "rose-pine",
      "rose-pine-dawn",
      "rose-pine-main",
      "rose-pine-moon",
    },
  },
  ["cocopon/iceberg.vim"] = {
    handle = "cocopon/iceberg.vim",
    url = "https://github.com/cocopon/iceberg.vim",
    github_stars = 2255,
    last_git_commit = "2024-06-19",
    priority = 0,
    source = "vsc",
    git_path = "cocopon-iceberg.vim",
    git_branch = nil,
    color_names = {
      "iceberg",
    },
  },
  ["projekt0n/github-nvim-theme"] = {
    handle = "projekt0n/github-nvim-theme",
    url = "https://github.com/projekt0n/github-nvim-theme",
    github_stars = 2200,
    last_git_commit = "2024-12-31",
    priority = 100,
    source = "asm",
    git_path = "projekt0n-github-nvim-theme",
    git_branch = nil,
    color_names = {
      "github_dark",
      "github_dark_colorblind",
      "github_dark_default",
      "github_dark_dimmed",
      "github_dark_high_contrast",
      "github_dark_tritanopia",
      "github_light",
      "github_light_colorblind",
      "github_light_default",
      "github_light_high_contrast",
      "github_light_tritanopia",
    },
  },
  ["sainnhe/gruvbox-material"] = {
    handle = "sainnhe/gruvbox-material",
    url = "https://github.com/sainnhe/gruvbox-material",
    github_stars = 2100,
    last_git_commit = "2025-01-16",
    priority = 100,
    source = "asm",
    git_path = "sainnhe-gruvbox-material",
    git_branch = nil,
    color_names = {
      "gruvbox-material",
    },
  },
  ["rakr/vim-one"] = {
    handle = "rakr/vim-one",
    url = "https://github.com/rakr/vim-one",
    github_stars = 2000,
    last_git_commit = "2020-12-14",
    priority = 0,
    source = "vsc",
    git_path = "rakr-vim-one",
    git_branch = nil,
    color_names = {
      "one",
    },
  },
  ["ellisonleao/gruvbox.nvim"] = {
    handle = "ellisonleao/gruvbox.nvim",
    url = "https://github.com/ellisonleao/gruvbox.nvim",
    github_stars = 2000,
    last_git_commit = "2024-11-24",
    priority = 100,
    source = "asm",
    git_path = "ellisonleao-gruvbox.nvim",
    git_branch = nil,
    color_names = {
      "gruvbox",
    },
  },
  ["ayu-theme/ayu-vim"] = {
    handle = "ayu-theme/ayu-vim",
    url = "https://github.com/ayu-theme/ayu-vim",
    github_stars = 1718,
    last_git_commit = "2024-07-15",
    priority = 0,
    source = "vsc",
    git_path = "ayu-theme-ayu-vim",
    git_branch = nil,
    color_names = {
      "ayu",
    },
  },
  ["sainnhe/sonokai"] = {
    handle = "sainnhe/sonokai",
    url = "https://github.com/sainnhe/sonokai",
    github_stars = 1700,
    last_git_commit = "2025-01-28",
    priority = 100,
    source = "asm",
    git_path = "sainnhe-sonokai",
    git_branch = nil,
    color_names = {
      "sonokai",
    },
  },
  ["navarasu/onedark.nvim"] = {
    handle = "navarasu/onedark.nvim",
    url = "https://github.com/navarasu/onedark.nvim",
    github_stars = 1700,
    last_git_commit = "2024-11-09",
    priority = 100,
    source = "asm",
    git_path = "navarasu-onedark.nvim",
    git_branch = nil,
    color_names = {
      "onedark",
    },
  },
  ["junegunn/seoul256.vim"] = {
    handle = "junegunn/seoul256.vim",
    url = "https://github.com/junegunn/seoul256.vim",
    github_stars = 1661,
    last_git_commit = "2023-05-03",
    priority = 0,
    source = "vsc",
    git_path = "junegunn-seoul256.vim",
    git_branch = nil,
    color_names = {
      "seoul256",
      "seoul256-light",
    },
  },
  ["ku1ik/vim-monokai"] = {
    handle = "ku1ik/vim-monokai",
    url = "https://github.com/ku1ik/vim-monokai",
    github_stars = 1445,
    last_git_commit = "2022-02-09",
    priority = 0,
    source = "vsc",
    git_path = "ku1ik-vim-monokai",
    git_branch = nil,
    color_names = {
      "monokai",
    },
  },
  ["dracula/vim"] = {
    handle = "dracula/vim",
    url = "https://github.com/dracula/vim",
    github_stars = 1300,
    last_git_commit = "2024-07-21",
    priority = 100,
    source = "asm",
    git_path = "dracula-vim",
    git_branch = nil,
    color_names = {
      "dracula",
    },
  },
  ["whatyouhide/vim-gotham"] = {
    handle = "whatyouhide/vim-gotham",
    url = "https://github.com/whatyouhide/vim-gotham",
    github_stars = 1264,
    last_git_commit = "2023-01-19",
    priority = 0,
    source = "vsc",
    git_path = "whatyouhide-vim-gotham",
    git_branch = nil,
    color_names = {
      "gotham",
      "gotham256",
    },
  },
  ["sjl/badwolf"] = {
    handle = "sjl/badwolf",
    url = "https://github.com/sjl/badwolf",
    github_stars = 1258,
    last_git_commit = "2024-05-23",
    priority = 0,
    source = "vsc",
    git_path = "sjl-badwolf",
    git_branch = nil,
    color_names = {
      "badwolf",
      "goodwolf",
    },
  },
  ["nyoom-engineering/oxocarbon.nvim"] = {
    handle = "nyoom-engineering/oxocarbon.nvim",
    url = "https://github.com/nyoom-engineering/oxocarbon.nvim",
    github_stars = 1200,
    last_git_commit = "2024-08-28",
    priority = 100,
    source = "asm",
    git_path = "nyoom-engineering-oxocarbon.nvim",
    git_branch = nil,
    color_names = {
      "oxocarbon",
    },
  },
  ["jacoborus/tender.vim"] = {
    handle = "jacoborus/tender.vim",
    url = "https://github.com/jacoborus/tender.vim",
    github_stars = 1166,
    last_git_commit = "2024-09-06",
    priority = 0,
    source = "vsc",
    git_path = "jacoborus-tender.vim",
    git_branch = nil,
    color_names = {
      "tender",
    },
  },
  ["mhartington/oceanic-next"] = {
    handle = "mhartington/oceanic-next",
    url = "https://github.com/mhartington/oceanic-next",
    github_stars = 1100,
    last_git_commit = "2023-05-01",
    priority = 100,
    source = "asm",
    git_path = "mhartington-oceanic-next",
    git_branch = nil,
    color_names = {
      "OceanicNext",
      "OceanicNextLight",
    },
  },
  ["lifepillar/vim-solarized8"] = {
    handle = "lifepillar/vim-solarized8",
    url = "https://github.com/lifepillar/vim-solarized8",
    github_stars = 1020,
    last_git_commit = "2024-05-21",
    priority = 0,
    source = "vsc",
    git_path = "lifepillar-vim-solarized8",
    git_branch = "neovim",
    color_names = {
      "solarized8",
      "solarized8_flat",
      "solarized8_high",
      "solarized8_low",
    },
  },
  ["marko-cerovac/material.nvim"] = {
    handle = "marko-cerovac/material.nvim",
    url = "https://github.com/marko-cerovac/material.nvim",
    github_stars = 1000,
    last_git_commit = "2024-12-29",
    priority = 100,
    source = "asm",
    git_path = "marko-cerovac-material.nvim",
    git_branch = nil,
    color_names = {
      "material",
      "material-darker",
      "material-deep-ocean",
      "material-lighter",
      "material-oceanic",
      "material-palenight",
    },
  },
  ["tomasiser/vim-code-dark"] = {
    handle = "tomasiser/vim-code-dark",
    url = "https://github.com/tomasiser/vim-code-dark",
    github_stars = 962,
    last_git_commit = "2024-05-21",
    priority = 100,
    source = "asm",
    git_path = "tomasiser-vim-code-dark",
    git_branch = nil,
    color_names = {
      "codedark",
    },
  },
  ["bluz71/vim-moonfly-colors"] = {
    handle = "bluz71/vim-moonfly-colors",
    url = "https://github.com/bluz71/vim-moonfly-colors",
    github_stars = 930,
    last_git_commit = "2025-02-01",
    priority = 100,
    source = "asm",
    git_path = "bluz71-vim-moonfly-colors",
    git_branch = nil,
    color_names = {
      "moonfly",
    },
  },
  ["sainnhe/edge"] = {
    handle = "sainnhe/edge",
    url = "https://github.com/sainnhe/edge",
    github_stars = 929,
    last_git_commit = "2025-01-16",
    priority = 100,
    source = "asm",
    git_path = "sainnhe-edge",
    git_branch = nil,
    color_names = {
      "edge",
    },
  },
  ["romainl/apprentice"] = {
    handle = "romainl/apprentice",
    url = "https://github.com/romainl/apprentice",
    github_stars = 899,
    last_git_commit = "2024-07-30",
    priority = 0,
    source = "vsc",
    git_path = "romainl-apprentice",
    git_branch = nil,
    color_names = {
      "apprentice",
    },
  },
  ["jnurmine/zenburn"] = {
    handle = "jnurmine/zenburn",
    url = "https://github.com/jnurmine/zenburn",
    github_stars = 896,
    last_git_commit = "2022-08-08",
    priority = 0,
    source = "vsc",
    git_path = "jnurmine-zenburn",
    git_branch = nil,
    color_names = {
      "zenburn",
    },
  },
  ["shaunsingh/nord.nvim"] = {
    handle = "shaunsingh/nord.nvim",
    url = "https://github.com/shaunsingh/nord.nvim",
    github_stars = 874,
    last_git_commit = "2023-12-20",
    priority = 100,
    source = "asm",
    git_path = "shaunsingh-nord.nvim",
    git_branch = nil,
    color_names = {
      "nord",
    },
  },
  ["srcery-colors/srcery-vim"] = {
    handle = "srcery-colors/srcery-vim",
    url = "https://github.com/srcery-colors/srcery-vim",
    github_stars = 845,
    last_git_commit = "2024-09-18",
    priority = 0,
    source = "vsc",
    git_path = "srcery-colors-srcery-vim",
    git_branch = nil,
    color_names = {
      "srcery",
    },
  },
  ["bluz71/vim-nightfly-colors"] = {
    handle = "bluz71/vim-nightfly-colors",
    url = "https://github.com/bluz71/vim-nightfly-colors",
    github_stars = 840,
    last_git_commit = "2025-02-01",
    priority = 100,
    source = "asm",
    git_path = "bluz71-vim-nightfly-colors",
    git_branch = nil,
    color_names = {
      "nightfly",
    },
  },
  ["scottmckendry/cyberdream.nvim"] = {
    handle = "scottmckendry/cyberdream.nvim",
    url = "https://github.com/scottmckendry/cyberdream.nvim",
    github_stars = 826,
    last_git_commit = "2025-01-21",
    priority = 100,
    source = "asm",
    git_path = "scottmckendry-cyberdream.nvim",
    git_branch = nil,
    color_names = {
      "cyberdream",
    },
  },
  ["pineapplegiant/spaceduck"] = {
    handle = "pineapplegiant/spaceduck",
    url = "https://github.com/pineapplegiant/spaceduck",
    github_stars = 816,
    last_git_commit = "2022-02-21",
    priority = 0,
    source = "vsc",
    git_path = "pineapplegiant-spaceduck",
    git_branch = nil,
    color_names = {
      "spaceduck",
    },
  },
  ["raphamorim/lucario"] = {
    handle = "raphamorim/lucario",
    url = "https://github.com/raphamorim/lucario",
    github_stars = 815,
    last_git_commit = "2024-11-08",
    priority = 0,
    source = "vsc",
    git_path = "raphamorim-lucario",
    git_branch = nil,
    color_names = {
      "lucario",
    },
  },
  ["zenbones-theme/zenbones.nvim"] = {
    handle = "zenbones-theme/zenbones.nvim",
    url = "https://github.com/zenbones-theme/zenbones.nvim",
    github_stars = 809,
    last_git_commit = "2025-01-09",
    priority = 100,
    source = "asm",
    git_path = "zenbones-theme-zenbones.nvim",
    git_branch = nil,
    color_names = {
      "duckbones",
      "forestbones",
      "kanagawabones",
      "neobones",
      "nordbones",
      "randombones",
      "rosebones",
      "seoulbones",
      "tokyobones",
      "vimbones",
      "zenbones",
      "zenburned",
      "zenwritten",
    },
  },
  ["ajmwagar/vim-deus"] = {
    handle = "ajmwagar/vim-deus",
    url = "https://github.com/ajmwagar/vim-deus",
    github_stars = 789,
    last_git_commit = "2021-03-28",
    priority = 0,
    source = "vsc",
    git_path = "ajmwagar-vim-deus",
    git_branch = nil,
    color_names = {
      "deus",
    },
  },
  ["alexvzyl/nordic.nvim"] = {
    handle = "alexvzyl/nordic.nvim",
    url = "https://github.com/alexvzyl/nordic.nvim",
    github_stars = 787,
    last_git_commit = "2025-01-21",
    priority = 100,
    source = "asm",
    git_path = "alexvzyl-nordic.nvim",
    git_branch = nil,
    color_names = {
      "nordic",
    },
  },
  ["savq/melange-nvim"] = {
    handle = "savq/melange-nvim",
    url = "https://github.com/savq/melange-nvim",
    github_stars = 766,
    last_git_commit = "2025-01-16",
    priority = 100,
    source = "asm",
    git_path = "savq-melange-nvim",
    git_branch = nil,
    color_names = {
      "melange",
    },
  },
  ["craftzdog/solarized-osaka.nvim"] = {
    handle = "craftzdog/solarized-osaka.nvim",
    url = "https://github.com/craftzdog/solarized-osaka.nvim",
    github_stars = 762,
    last_git_commit = "2025-01-23",
    priority = 0,
    source = "vsc",
    git_path = "craftzdog-solarized-osaka.nvim",
    git_branch = nil,
    color_names = {
      "solarized-osaka",
      "solarized-osaka-day",
    },
  },
  ["mofiqul/vscode.nvim"] = {
    handle = "mofiqul/vscode.nvim",
    url = "https://github.com/mofiqul/vscode.nvim",
    github_stars = 761,
    last_git_commit = "2025-01-09",
    priority = 100,
    source = "asm",
    git_path = "mofiqul-vscode.nvim",
    git_branch = nil,
    color_names = {
      "vscode",
    },
  },
  ["fenetikm/falcon"] = {
    handle = "fenetikm/falcon",
    url = "https://github.com/fenetikm/falcon",
    github_stars = 757,
    last_git_commit = "2024-12-02",
    priority = 100,
    source = "asm",
    git_path = "fenetikm-falcon",
    git_branch = nil,
    color_names = {
      "falcon",
    },
  },
  ["tjdevries/colorbuddy.nvim"] = {
    handle = "tjdevries/colorbuddy.nvim",
    url = "https://github.com/tjdevries/colorbuddy.nvim",
    github_stars = 685,
    last_git_commit = "2024-05-08",
    priority = 0,
    source = "vsc",
    git_path = "tjdevries-colorbuddy.nvim",
    git_branch = nil,
    color_names = {
      "colorbuddy",
      "gruvbuddy",
    },
  },
  ["embark-theme/vim"] = {
    handle = "embark-theme/vim",
    url = "https://github.com/embark-theme/vim",
    github_stars = 669,
    last_git_commit = "2025-01-26",
    priority = 100,
    source = "asm",
    git_path = "embark-theme-vim",
    git_branch = nil,
    color_names = {
      "embark",
    },
  },
  ["drewtempelmeyer/palenight.vim"] = {
    handle = "drewtempelmeyer/palenight.vim",
    url = "https://github.com/drewtempelmeyer/palenight.vim",
    github_stars = 658,
    last_git_commit = "2023-04-27",
    priority = 0,
    source = "vsc",
    git_path = "drewtempelmeyer-palenight.vim",
    git_branch = nil,
    color_names = {
      "palenight",
    },
  },
  ["lunacookies/vim-colors-xcode"] = {
    handle = "lunacookies/vim-colors-xcode",
    url = "https://github.com/lunacookies/vim-colors-xcode",
    github_stars = 615,
    last_git_commit = "2024-10-25",
    priority = 0,
    source = "vsc",
    git_path = "lunacookies-vim-colors-xcode",
    git_branch = nil,
    color_names = {
      "xcode",
      "xcodedark",
      "xcodedarkhc",
      "xcodehc",
      "xcodelight",
      "xcodelighthc",
      "xcodewwdc",
    },
  },
  ["preservim/vim-colors-pencil"] = {
    handle = "preservim/vim-colors-pencil",
    url = "https://github.com/preservim/vim-colors-pencil",
    github_stars = 609,
    last_git_commit = "2022-05-07",
    priority = 0,
    source = "vsc",
    git_path = "preservim-vim-colors-pencil",
    git_branch = nil,
    color_names = {
      "pencil",
    },
  },
  ["challenger-deep-theme/vim"] = {
    handle = "challenger-deep-theme/vim",
    url = "https://github.com/challenger-deep-theme/vim",
    github_stars = 603,
    last_git_commit = "2022-04-25",
    priority = 0,
    source = "vsc",
    git_path = "challenger-deep-theme-vim",
    git_branch = nil,
    color_names = {
      "challenger_deep",
    },
  },
  ["liuchengxu/space-vim-dark"] = {
    handle = "liuchengxu/space-vim-dark",
    url = "https://github.com/liuchengxu/space-vim-dark",
    github_stars = 601,
    last_git_commit = "2023-11-04",
    priority = 0,
    source = "vsc",
    git_path = "liuchengxu-space-vim-dark",
    git_branch = nil,
    color_names = {
      "space-vim-dark",
    },
  },
  ["wadackel/vim-dogrun"] = {
    handle = "wadackel/vim-dogrun",
    url = "https://github.com/wadackel/vim-dogrun",
    github_stars = 581,
    last_git_commit = "2024-08-25",
    priority = 0,
    source = "vsc",
    git_path = "wadackel-vim-dogrun",
    git_branch = nil,
    color_names = {
      "dogrun",
    },
  },
  ["rmehri01/onenord.nvim"] = {
    handle = "rmehri01/onenord.nvim",
    url = "https://github.com/rmehri01/onenord.nvim",
    github_stars = 548,
    last_git_commit = "2025-01-03",
    priority = 100,
    source = "asm",
    git_path = "rmehri01-onenord.nvim",
    git_branch = nil,
    color_names = {
      "onenord",
      "onenord-light",
    },
  },
  ["kristijanhusak/vim-hybrid-material"] = {
    handle = "kristijanhusak/vim-hybrid-material",
    url = "https://github.com/kristijanhusak/vim-hybrid-material",
    github_stars = 548,
    last_git_commit = "2020-06-16",
    priority = 0,
    source = "vsc",
    git_path = "kristijanhusak-vim-hybrid-material",
    git_branch = nil,
    color_names = {
      "hybrid_material",
      "hybrid_reverse",
    },
  },
  ["rrethy/base16-nvim"] = {
    handle = "rrethy/base16-nvim",
    url = "https://github.com/rrethy/base16-nvim",
    github_stars = 534,
    last_git_commit = "2024-05-23",
    priority = 100,
    source = "asm",
    git_path = "rrethy-base16-nvim",
    git_branch = nil,
    color_names = {
      "base16-3024",
      "base16-apathy",
      "base16-apprentice",
      "base16-ashes",
      "base16-atelier-cave",
      "base16-atelier-cave-light",
      "base16-atelier-dune",
      "base16-atelier-dune-light",
      "base16-atelier-estuary",
      "base16-atelier-estuary-light",
      "base16-atelier-forest",
      "base16-atelier-forest-light",
      "base16-atelier-heath",
      "base16-atelier-heath-light",
      "base16-atelier-lakeside",
      "base16-atelier-lakeside-light",
      "base16-atelier-plateau",
      "base16-atelier-plateau-light",
      "base16-atelier-savanna",
      "base16-atelier-savanna-light",
      "base16-atelier-seaside",
      "base16-atelier-seaside-light",
      "base16-atelier-sulphurpool",
      "base16-atelier-sulphurpool-light",
      "base16-atlas",
      "base16-ayu-dark",
      "base16-ayu-light",
      "base16-ayu-mirage",
      "base16-bespin",
      "base16-black-metal",
      "base16-black-metal-bathory",
      "base16-black-metal-burzum",
      "base16-black-metal-dark-funeral",
      "base16-black-metal-gorgoroth",
      "base16-black-metal-immortal",
      "base16-black-metal-khold",
      "base16-black-metal-marduk",
      "base16-black-metal-mayhem",
      "base16-black-metal-nile",
      "base16-black-metal-venom",
      "base16-blueforest",
      "base16-blueish",
      "base16-brewer",
      "base16-bright",
      "base16-brogrammer",
      "base16-brushtrees",
      "base16-brushtrees-dark",
      "base16-catppuccin",
      "base16-catppuccin-frappe",
      "base16-catppuccin-latte",
      "base16-catppuccin-macchiato",
      "base16-catppuccin-mocha",
      "base16-chalk",
      "base16-circus",
      "base16-classic-dark",
      "base16-classic-light",
      "base16-codeschool",
      "base16-colors",
      "base16-cupcake",
      "base16-cupertino",
      "base16-da-one-black",
      "base16-da-one-gray",
      "base16-da-one-ocean",
      "base16-da-one-paper",
      "base16-da-one-sea",
      "base16-da-one-white",
      "base16-danqing",
      "base16-danqing-light",
      "base16-darcula",
      "base16-darkmoss",
      "base16-darktooth",
      "base16-darkviolet",
      "base16-decaf",
      "base16-default-dark",
      "base16-default-light",
      "base16-dirtysea",
      "base16-dracula",
      "base16-edge-dark",
      "base16-edge-light",
      "base16-eighties",
      "base16-embers",
      "base16-emil",
      "base16-equilibrium-dark",
      "base16-equilibrium-gray-dark",
      "base16-equilibrium-gray-light",
      "base16-equilibrium-light",
      "base16-espresso",
      "base16-eva",
      "base16-eva-dim",
      "base16-evenok-dark",
      "base16-everforest",
      "base16-flat",
      "base16-framer",
      "base16-fruit-soda",
      "base16-gigavolt",
      "base16-github",
      "base16-google-dark",
      "base16-google-light",
      "base16-gotham",
      "base16-grayscale-dark",
      "base16-grayscale-light",
      "base16-greenscreen",
      "base16-gruber",
      "base16-gruvbox-dark-hard",
      "base16-gruvbox-dark-medium",
      "base16-gruvbox-dark-pale",
      "base16-gruvbox-dark-soft",
      "base16-gruvbox-light-hard",
      "base16-gruvbox-light-medium",
      "base16-gruvbox-light-soft",
      "base16-gruvbox-material-dark-hard",
      "base16-gruvbox-material-dark-medium",
      "base16-gruvbox-material-dark-soft",
      "base16-gruvbox-material-light-hard",
      "base16-gruvbox-material-light-medium",
      "base16-gruvbox-material-light-soft",
      "base16-hardcore",
      "base16-harmonic-dark",
      "base16-harmonic-light",
      "base16-harmonic16-dark",
      "base16-harmonic16-light",
      "base16-heetch",
      "base16-heetch-light",
      "base16-helios",
      "base16-hopscotch",
      "base16-horizon-dark",
      "base16-horizon-light",
      "base16-horizon-terminal-dark",
      "base16-horizon-terminal-light",
      "base16-humanoid-dark",
      "base16-humanoid-light",
      "base16-ia-dark",
      "base16-ia-light",
      "base16-icy",
      "base16-irblack",
      "base16-isotope",
      "base16-kanagawa",
      "base16-katy",
      "base16-kimber",
      "base16-lime",
      "base16-macintosh",
      "base16-marrakesh",
      "base16-materia",
      "base16-material",
      "base16-material-darker",
      "base16-material-lighter",
      "base16-material-palenight",
      "base16-material-vivid",
      "base16-mellow-purple",
      "base16-mexico-light",
      "base16-mocha",
      "base16-monokai",
      "base16-mountain",
      "base16-nebula",
      "base16-nord",
      "base16-nova",
      "base16-ocean",
      "base16-oceanicnext",
      "base16-one-light",
      "base16-onedark",
      "base16-outrun-dark",
      "base16-pandora",
      "base16-papercolor-dark",
      "base16-papercolor-light",
      "base16-paraiso",
      "base16-pasque",
      "base16-phd",
      "base16-pico",
      "base16-pinky",
      "base16-pop",
      "base16-porple",
      "base16-primer-dark",
      "base16-primer-dark-dimmed",
      "base16-primer-light",
      "base16-purpledream",
      "base16-qualia",
      "base16-railscasts",
      "base16-rebecca",
      "base16-rose-pine",
      "base16-rose-pine-dawn",
      "base16-rose-pine-moon",
      "base16-sagelight",
      "base16-sakura",
      "base16-sandcastle",
      "base16-schemer-dark",
      "base16-schemer-medium",
      "base16-selenized-black",
      "base16-selenized-dark",
      "base16-selenized-light",
      "base16-selenized-white",
      "base16-seti",
      "base16-shades-of-purple",
      "base16-shadesmear-dark",
      "base16-shadesmear-light",
      "base16-shapeshifter",
      "base16-silk-dark",
      "base16-silk-light",
      "base16-snazzy",
      "base16-solarflare",
      "base16-solarflare-light",
      "base16-solarized-dark",
      "base16-solarized-light",
      "base16-spaceduck",
      "base16-spacemacs",
      "base16-standardized-dark",
      "base16-standardized-light",
      "base16-stella",
      "base16-still-alive",
      "base16-summercamp",
      "base16-summerfruit-dark",
      "base16-summerfruit-light",
      "base16-synth-midnight-dark",
      "base16-synth-midnight-light",
      "base16-tango",
      "base16-tender",
      "base16-tokyo-city-dark",
      "base16-tokyo-city-light",
      "base16-tokyo-city-terminal-dark",
      "base16-tokyo-city-terminal-light",
      "base16-tokyo-night-dark",
      "base16-tokyo-night-light",
      "base16-tokyo-night-storm",
      "base16-tokyo-night-terminal-dark",
      "base16-tokyo-night-terminal-light",
      "base16-tokyo-night-terminal-storm",
      "base16-tokyodark",
      "base16-tokyodark-terminal",
      "base16-tomorrow",
      "base16-tomorrow-night",
      "base16-tomorrow-night-eighties",
      "base16-tube",
      "base16-twilight",
      "base16-unikitty-dark",
      "base16-unikitty-light",
      "base16-unikitty-reversible",
      "base16-uwunicorn",
      "base16-vice",
      "base16-vulcan",
      "base16-windows-10",
      "base16-windows-10-light",
      "base16-windows-95",
      "base16-windows-95-light",
      "base16-windows-highcontrast",
      "base16-windows-highcontrast-light",
      "base16-windows-nt",
      "base16-windows-nt-light",
      "base16-woodland",
      "base16-xcode-dusk",
      "base16-zenbones",
      "base16-zenburn",
    },
  },
  ["lifepillar/vim-gruvbox8"] = {
    handle = "lifepillar/vim-gruvbox8",
    url = "https://github.com/lifepillar/vim-gruvbox8",
    github_stars = 531,
    last_git_commit = "2023-08-04",
    priority = 0,
    source = "vsc",
    git_path = "lifepillar-vim-gruvbox8",
    git_branch = "neovim",
    color_names = {
      "gruvbox8",
      "gruvbox8_hard",
      "gruvbox8_soft",
    },
  },
  ["jaredgorski/spacecamp"] = {
    handle = "jaredgorski/spacecamp",
    url = "https://github.com/jaredgorski/spacecamp",
    github_stars = 524,
    last_git_commit = "2023-08-25",
    priority = 0,
    source = "vsc",
    git_path = "jaredgorski-spacecamp",
    git_branch = nil,
    color_names = {
      "spacecamp",
      "spacecamp_lite",
    },
  },
  ["rigellute/rigel"] = {
    handle = "rigellute/rigel",
    url = "https://github.com/rigellute/rigel",
    github_stars = 513,
    last_git_commit = "2024-01-11",
    priority = 0,
    source = "vsc",
    git_path = "rigellute-rigel",
    git_branch = nil,
    color_names = {
      "rigel",
    },
  },
  ["tiagovla/tokyodark.nvim"] = {
    handle = "tiagovla/tokyodark.nvim",
    url = "https://github.com/tiagovla/tokyodark.nvim",
    github_stars = 508,
    last_git_commit = "2025-01-02",
    priority = 100,
    source = "asm",
    git_path = "tiagovla-tokyodark.nvim",
    git_branch = nil,
    color_names = {
      "tokyodark",
    },
  },
  ["loctvl842/monokai-pro.nvim"] = {
    handle = "loctvl842/monokai-pro.nvim",
    url = "https://github.com/loctvl842/monokai-pro.nvim",
    github_stars = 508,
    last_git_commit = "2024-12-16",
    priority = 0,
    source = "vsc",
    git_path = "loctvl842-monokai-pro.nvim",
    git_branch = nil,
    color_names = {
      "monokai-pro",
      "monokai-pro-classic",
      "monokai-pro-default",
      "monokai-pro-light",
      "monokai-pro-machine",
      "monokai-pro-octagon",
      "monokai-pro-ristretto",
      "monokai-pro-spectrum",
    },
  },
  ["haishanh/night-owl.vim"] = {
    handle = "haishanh/night-owl.vim",
    url = "https://github.com/haishanh/night-owl.vim",
    github_stars = 504,
    last_git_commit = "2020-12-25",
    priority = 0,
    source = "vsc",
    git_path = "haishanh-night-owl.vim",
    git_branch = nil,
    color_names = {
      "night-owl",
    },
  },
}