return {
  ["mhartington/oceanic-next"] = {
    handle = "mhartington/oceanic-next",
    color_name = "OceanicNext",
    plugin_name = "oceanic-next",
    url = "https://github.com/mhartington/oceanic-next",
    install_path = "mhartington-oceanic-next",
    git_branch = nil,
  },
  ["nlknguyen/papercolor-theme"] = {
    handle = "nlknguyen/papercolor-theme",
    color_name = "PaperColor",
    plugin_name = "papercolor-theme",
    url = "https://github.com/nlknguyen/papercolor-theme",
    install_path = "nlknguyen-papercolor-theme",
    git_branch = nil,
  },
  ["romainl/apprentice"] = {
    handle = "romainl/apprentice",
    color_name = "apprentice",
    plugin_name = "apprentice",
    url = "https://github.com/romainl/apprentice",
    install_path = "romainl-apprentice",
    git_branch = nil,
  },
  ["ayu-theme/ayu-vim"] = {
    handle = "ayu-theme/ayu-vim",
    color_name = "ayu",
    plugin_name = "ayu-vim",
    url = "https://github.com/ayu-theme/ayu-vim",
    install_path = "ayu-theme-ayu-vim",
    git_branch = nil,
  },
  ["catppuccin/nvim"] = {
    handle = "catppuccin/nvim",
    color_name = "catppuccin",
    plugin_name = "catppuccin",
    url = "https://github.com/catppuccin/nvim",
    install_path = "catppuccin-nvim",
    git_branch = nil,
  },
  ["tomasiser/vim-code-dark"] = {
    handle = "tomasiser/vim-code-dark",
    color_name = "codedark",
    plugin_name = "vim-code-dark",
    url = "https://github.com/tomasiser/vim-code-dark",
    install_path = "tomasiser-vim-code-dark",
    git_branch = nil,
  },
  ["scottmckendry/cyberdream.nvim"] = {
    handle = "scottmckendry/cyberdream.nvim",
    color_name = "cyberdream",
    plugin_name = "cyberdream.nvim",
    url = "https://github.com/scottmckendry/cyberdream.nvim",
    install_path = "scottmckendry-cyberdream.nvim",
    git_branch = nil,
  },
  ["ajmwagar/vim-deus"] = {
    handle = "ajmwagar/vim-deus",
    color_name = "deus",
    plugin_name = "vim-deus",
    url = "https://github.com/ajmwagar/vim-deus",
    install_path = "ajmwagar-vim-deus",
    git_branch = nil,
  },
  ["dracula/vim"] = {
    handle = "dracula/vim",
    color_name = "dracula",
    plugin_name = "dracula",
    url = "https://github.com/dracula/vim",
    install_path = "dracula-vim",
    git_branch = nil,
  },
  ["sainnhe/edge"] = {
    handle = "sainnhe/edge",
    color_name = "edge",
    plugin_name = "edge",
    url = "https://github.com/sainnhe/edge",
    install_path = "sainnhe-edge",
    git_branch = nil,
  },
  ["sainnhe/everforest"] = {
    handle = "sainnhe/everforest",
    color_name = "everforest",
    plugin_name = "everforest",
    url = "https://github.com/sainnhe/everforest",
    install_path = "sainnhe-everforest",
    git_branch = nil,
  },
  ["fenetikm/falcon"] = {
    handle = "fenetikm/falcon",
    color_name = "falcon",
    plugin_name = "falcon",
    url = "https://github.com/fenetikm/falcon",
    install_path = "fenetikm-falcon",
    git_branch = nil,
  },
  ["projekt0n/github-nvim-theme"] = {
    handle = "projekt0n/github-nvim-theme",
    color_name = "github_dark",
    plugin_name = "github-nvim-theme",
    url = "https://github.com/projekt0n/github-nvim-theme",
    install_path = "projekt0n-github-nvim-theme",
    git_branch = nil,
  },
  ["whatyouhide/vim-gotham"] = {
    handle = "whatyouhide/vim-gotham",
    color_name = "gotham",
    plugin_name = "vim-gotham",
    url = "https://github.com/whatyouhide/vim-gotham",
    install_path = "whatyouhide-vim-gotham",
    git_branch = nil,
  },
  ["ellisonleao/gruvbox.nvim"] = {
    handle = "ellisonleao/gruvbox.nvim",
    color_name = "gruvbox",
    plugin_name = "gruvbox.nvim",
    url = "https://github.com/ellisonleao/gruvbox.nvim",
    install_path = "ellisonleao-gruvbox.nvim",
    git_branch = nil,
  },
  ["sainnhe/gruvbox-material"] = {
    handle = "sainnhe/gruvbox-material",
    color_name = "gruvbox-material",
    plugin_name = "gruvbox-material",
    url = "https://github.com/sainnhe/gruvbox-material",
    install_path = "sainnhe-gruvbox-material",
    git_branch = nil,
  },
  ["cocopon/iceberg.vim"] = {
    handle = "cocopon/iceberg.vim",
    color_name = "iceberg",
    plugin_name = "iceberg.vim",
    url = "https://github.com/cocopon/iceberg.vim",
    install_path = "cocopon-iceberg.vim",
    git_branch = nil,
  },
  ["nanotech/jellybeans.vim"] = {
    handle = "nanotech/jellybeans.vim",
    color_name = "jellybeans",
    plugin_name = "jellybeans.vim",
    url = "https://github.com/nanotech/jellybeans.vim",
    install_path = "nanotech-jellybeans.vim",
    git_branch = nil,
  },
  ["rebelot/kanagawa.nvim"] = {
    handle = "rebelot/kanagawa.nvim",
    color_name = "kanagawa",
    plugin_name = "kanagawa.nvim",
    url = "https://github.com/rebelot/kanagawa.nvim",
    install_path = "rebelot-kanagawa.nvim",
    git_branch = nil,
  },
  ["marko-cerovac/material.nvim"] = {
    handle = "marko-cerovac/material.nvim",
    color_name = "material",
    plugin_name = "material.nvim",
    url = "https://github.com/marko-cerovac/material.nvim",
    install_path = "marko-cerovac-material.nvim",
    git_branch = nil,
  },
  ["savq/melange-nvim"] = {
    handle = "savq/melange-nvim",
    color_name = "melange",
    plugin_name = "melange-nvim",
    url = "https://github.com/savq/melange-nvim",
    install_path = "savq-melange-nvim",
    git_branch = nil,
  },
  ["bluz71/vim-moonfly-colors"] = {
    handle = "bluz71/vim-moonfly-colors",
    color_name = "moonfly",
    plugin_name = "vim-moonfly-colors",
    url = "https://github.com/bluz71/vim-moonfly-colors",
    install_path = "bluz71-vim-moonfly-colors",
    git_branch = nil,
  },
  ["bluz71/vim-nightfly-colors"] = {
    handle = "bluz71/vim-nightfly-colors",
    color_name = "nightfly",
    plugin_name = "vim-nightfly-colors",
    url = "https://github.com/bluz71/vim-nightfly-colors",
    install_path = "bluz71-vim-nightfly-colors",
    git_branch = nil,
  },
  ["edeneast/nightfox.nvim"] = {
    handle = "edeneast/nightfox.nvim",
    color_name = "nightfox",
    plugin_name = "nightfox.nvim",
    url = "https://github.com/edeneast/nightfox.nvim",
    install_path = "edeneast-nightfox.nvim",
    git_branch = nil,
  },
  ["shaunsingh/nord.nvim"] = {
    handle = "shaunsingh/nord.nvim",
    color_name = "nord",
    plugin_name = "nord.nvim",
    url = "https://github.com/shaunsingh/nord.nvim",
    install_path = "shaunsingh-nord.nvim",
    git_branch = nil,
  },
  ["alexvzyl/nordic.nvim"] = {
    handle = "alexvzyl/nordic.nvim",
    color_name = "nordic",
    plugin_name = "nordic.nvim",
    url = "https://github.com/alexvzyl/nordic.nvim",
    install_path = "alexvzyl-nordic.nvim",
    git_branch = nil,
  },
  ["rakr/vim-one"] = {
    handle = "rakr/vim-one",
    color_name = "one",
    plugin_name = "vim-one",
    url = "https://github.com/rakr/vim-one",
    install_path = "rakr-vim-one",
    git_branch = nil,
  },
  ["olimorris/onedarkpro.nvim"] = {
    handle = "olimorris/onedarkpro.nvim",
    color_name = "onedark",
    plugin_name = "onedarkpro.nvim",
    url = "https://github.com/olimorris/onedarkpro.nvim",
    install_path = "olimorris-onedarkpro.nvim",
    git_branch = nil,
  },
  ["nyoom-engineering/oxocarbon.nvim"] = {
    handle = "nyoom-engineering/oxocarbon.nvim",
    color_name = "oxocarbon",
    plugin_name = "oxocarbon.nvim",
    url = "https://github.com/nyoom-engineering/oxocarbon.nvim",
    install_path = "nyoom-engineering-oxocarbon.nvim",
    git_branch = nil,
  },
  ["rose-pine/neovim"] = {
    handle = "rose-pine/neovim",
    color_name = "rose-pine",
    plugin_name = "rose-pine",
    url = "https://github.com/rose-pine/neovim",
    install_path = "rose-pine-neovim",
    git_branch = nil,
  },
  ["junegunn/seoul256.vim"] = {
    handle = "junegunn/seoul256.vim",
    color_name = "seoul256",
    plugin_name = "seoul256.vim",
    url = "https://github.com/junegunn/seoul256.vim",
    install_path = "junegunn-seoul256.vim",
    git_branch = nil,
  },
  ["craftzdog/solarized-osaka.nvim"] = {
    handle = "craftzdog/solarized-osaka.nvim",
    color_name = "solarized-osaka",
    plugin_name = "solarized-osaka.nvim",
    url = "https://github.com/craftzdog/solarized-osaka.nvim",
    install_path = "craftzdog-solarized-osaka.nvim",
    git_branch = nil,
  },
  ["lifepillar/vim-solarized8"] = {
    handle = "lifepillar/vim-solarized8",
    color_name = "solarized8",
    plugin_name = "vim-solarized8",
    url = "https://codeberg.org/lifepillar/vim-solarized8",
    install_path = "lifepillar-vim-solarized8",
    git_branch = "neovim",
  },
  ["sainnhe/sonokai"] = {
    handle = "sainnhe/sonokai",
    color_name = "sonokai",
    plugin_name = "sonokai",
    url = "https://github.com/sainnhe/sonokai",
    install_path = "sainnhe-sonokai",
    git_branch = nil,
  },
  ["jacoborus/tender.vim"] = {
    handle = "jacoborus/tender.vim",
    color_name = "tender",
    plugin_name = "tender.vim",
    url = "https://github.com/jacoborus/tender.vim",
    install_path = "jacoborus-tender.vim",
    git_branch = nil,
  },
  ["folke/tokyonight.nvim"] = {
    handle = "folke/tokyonight.nvim",
    color_name = "tokyonight",
    plugin_name = "tokyonight.nvim",
    url = "https://github.com/folke/tokyonight.nvim",
    install_path = "folke-tokyonight.nvim",
    git_branch = nil,
  },
  ["vague-theme/vague.nvim"] = {
    handle = "vague-theme/vague.nvim",
    color_name = "vague",
    plugin_name = "vague.nvim",
    url = "https://github.com/vague-theme/vague.nvim",
    install_path = "vague-theme-vague.nvim",
    git_branch = nil,
  },
  ["mofiqul/vscode.nvim"] = {
    handle = "mofiqul/vscode.nvim",
    color_name = "vscode",
    plugin_name = "vscode.nvim",
    url = "https://github.com/mofiqul/vscode.nvim",
    install_path = "mofiqul-vscode.nvim",
    git_branch = nil,
  },
  ["zenbones-theme/zenbones.nvim"] = {
    handle = "zenbones-theme/zenbones.nvim",
    color_name = "zenbones",
    plugin_name = "zenbones.nvim",
    url = "https://github.com/zenbones-theme/zenbones.nvim",
    install_path = "zenbones-theme-zenbones.nvim",
    git_branch = nil,
  },
}
