return {
  tokyonight = {
    handle = "folke/tokyonight.nvim",
    url = "https://github.com/folke/tokyonight.nvim",
    github_stars = 5900,
    last_git_commit = "2024-07-24",
    priority = 100,
    source = "asm",
    git_path = "folke-tokyonight.nvim",
    git_branch = nil,
    color_names = {
      "tokyonight",
      "tokyonight-day",
      "tokyonight-moon",
      "tokyonight-night",
      "tokyonight-storm",
    },
  },
  ["tokyonight-day"] = {
    handle = "folke/tokyonight.nvim",
    url = "https://github.com/folke/tokyonight.nvim",
    github_stars = 5900,
    last_git_commit = "2024-07-24",
    priority = 100,
    source = "asm",
    git_path = "folke-tokyonight.nvim",
    git_branch = nil,
    color_names = {
      "tokyonight",
      "tokyonight-day",
      "tokyonight-moon",
      "tokyonight-night",
      "tokyonight-storm",
    },
  },
  ["tokyonight-moon"] = {
    handle = "folke/tokyonight.nvim",
    url = "https://github.com/folke/tokyonight.nvim",
    github_stars = 5900,
    last_git_commit = "2024-07-24",
    priority = 100,
    source = "asm",
    git_path = "folke-tokyonight.nvim",
    git_branch = nil,
    color_names = {
      "tokyonight",
      "tokyonight-day",
      "tokyonight-moon",
      "tokyonight-night",
      "tokyonight-storm",
    },
  },
  ["tokyonight-night"] = {
    handle = "folke/tokyonight.nvim",
    url = "https://github.com/folke/tokyonight.nvim",
    github_stars = 5900,
    last_git_commit = "2024-07-24",
    priority = 100,
    source = "asm",
    git_path = "folke-tokyonight.nvim",
    git_branch = nil,
    color_names = {
      "tokyonight",
      "tokyonight-day",
      "tokyonight-moon",
      "tokyonight-night",
      "tokyonight-storm",
    },
  },
  ["tokyonight-storm"] = {
    handle = "folke/tokyonight.nvim",
    url = "https://github.com/folke/tokyonight.nvim",
    github_stars = 5900,
    last_git_commit = "2024-07-24",
    priority = 100,
    source = "asm",
    git_path = "folke-tokyonight.nvim",
    git_branch = nil,
    color_names = {
      "tokyonight",
      "tokyonight-day",
      "tokyonight-moon",
      "tokyonight-night",
      "tokyonight-storm",
    },
  },
  catppuccin = {
    handle = "catppuccin/nvim",
    url = "https://github.com/catppuccin/nvim",
    github_stars = 5100,
    last_git_commit = "2024-07-25",
    priority = 100,
    source = "asm",
    git_path = "catppuccin-nvim",
    git_branch = nil,
    color_names = {
      "catppuccin",
      "catppuccin-frappe",
      "catppuccin-latte",
      "catppuccin-macchiato",
      "catppuccin-mocha",
    },
  },
  ["catppuccin-frappe"] = {
    handle = "catppuccin/nvim",
    url = "https://github.com/catppuccin/nvim",
    github_stars = 5100,
    last_git_commit = "2024-07-25",
    priority = 100,
    source = "asm",
    git_path = "catppuccin-nvim",
    git_branch = nil,
    color_names = {
      "catppuccin",
      "catppuccin-frappe",
      "catppuccin-latte",
      "catppuccin-macchiato",
      "catppuccin-mocha",
    },
  },
  ["catppuccin-latte"] = {
    handle = "catppuccin/nvim",
    url = "https://github.com/catppuccin/nvim",
    github_stars = 5100,
    last_git_commit = "2024-07-25",
    priority = 100,
    source = "asm",
    git_path = "catppuccin-nvim",
    git_branch = nil,
    color_names = {
      "catppuccin",
      "catppuccin-frappe",
      "catppuccin-latte",
      "catppuccin-macchiato",
      "catppuccin-mocha",
    },
  },
  ["catppuccin-macchiato"] = {
    handle = "catppuccin/nvim",
    url = "https://github.com/catppuccin/nvim",
    github_stars = 5100,
    last_git_commit = "2024-07-25",
    priority = 100,
    source = "asm",
    git_path = "catppuccin-nvim",
    git_branch = nil,
    color_names = {
      "catppuccin",
      "catppuccin-frappe",
      "catppuccin-latte",
      "catppuccin-macchiato",
      "catppuccin-mocha",
    },
  },
  ["catppuccin-mocha"] = {
    handle = "catppuccin/nvim",
    url = "https://github.com/catppuccin/nvim",
    github_stars = 5100,
    last_git_commit = "2024-07-25",
    priority = 100,
    source = "asm",
    git_path = "catppuccin-nvim",
    git_branch = nil,
    color_names = {
      "catppuccin",
      "catppuccin-frappe",
      "catppuccin-latte",
      "catppuccin-macchiato",
      "catppuccin-mocha",
    },
  },
  kanagawa = {
    handle = "rebelot/kanagawa.nvim",
    url = "https://github.com/rebelot/kanagawa.nvim",
    github_stars = 3900,
    last_git_commit = "2024-07-03",
    priority = 100,
    source = "asm",
    git_path = "rebelot-kanagawa.nvim",
    git_branch = nil,
    color_names = {
      "kanagawa",
      "kanagawa-dragon",
      "kanagawa-lotus",
      "kanagawa-wave",
    },
  },
  ["kanagawa-dragon"] = {
    handle = "rebelot/kanagawa.nvim",
    url = "https://github.com/rebelot/kanagawa.nvim",
    github_stars = 3900,
    last_git_commit = "2024-07-03",
    priority = 100,
    source = "asm",
    git_path = "rebelot-kanagawa.nvim",
    git_branch = nil,
    color_names = {
      "kanagawa",
      "kanagawa-dragon",
      "kanagawa-lotus",
      "kanagawa-wave",
    },
  },
  ["kanagawa-lotus"] = {
    handle = "rebelot/kanagawa.nvim",
    url = "https://github.com/rebelot/kanagawa.nvim",
    github_stars = 3900,
    last_git_commit = "2024-07-03",
    priority = 100,
    source = "asm",
    git_path = "rebelot-kanagawa.nvim",
    git_branch = nil,
    color_names = {
      "kanagawa",
      "kanagawa-dragon",
      "kanagawa-lotus",
      "kanagawa-wave",
    },
  },
  ["kanagawa-wave"] = {
    handle = "rebelot/kanagawa.nvim",
    url = "https://github.com/rebelot/kanagawa.nvim",
    github_stars = 3900,
    last_git_commit = "2024-07-03",
    priority = 100,
    source = "asm",
    git_path = "rebelot-kanagawa.nvim",
    git_branch = nil,
    color_names = {
      "kanagawa",
      "kanagawa-dragon",
      "kanagawa-lotus",
      "kanagawa-wave",
    },
  },
  carbonfox = {
    handle = "edeneast/nightfox.nvim",
    url = "https://github.com/edeneast/nightfox.nvim",
    github_stars = 2900,
    last_git_commit = "2024-07-22",
    priority = 100,
    source = "asm",
    git_path = "edeneast-nightfox.nvim",
    git_branch = nil,
    color_names = {
      "carbonfox",
      "dawnfox",
      "dayfox",
      "duskfox",
      "nightfox",
      "nordfox",
      "terafox",
    },
  },
  dawnfox = {
    handle = "edeneast/nightfox.nvim",
    url = "https://github.com/edeneast/nightfox.nvim",
    github_stars = 2900,
    last_git_commit = "2024-07-22",
    priority = 100,
    source = "asm",
    git_path = "edeneast-nightfox.nvim",
    git_branch = nil,
    color_names = {
      "carbonfox",
      "dawnfox",
      "dayfox",
      "duskfox",
      "nightfox",
      "nordfox",
      "terafox",
    },
  },
  dayfox = {
    handle = "edeneast/nightfox.nvim",
    url = "https://github.com/edeneast/nightfox.nvim",
    github_stars = 2900,
    last_git_commit = "2024-07-22",
    priority = 100,
    source = "asm",
    git_path = "edeneast-nightfox.nvim",
    git_branch = nil,
    color_names = {
      "carbonfox",
      "dawnfox",
      "dayfox",
      "duskfox",
      "nightfox",
      "nordfox",
      "terafox",
    },
  },
  duskfox = {
    handle = "edeneast/nightfox.nvim",
    url = "https://github.com/edeneast/nightfox.nvim",
    github_stars = 2900,
    last_git_commit = "2024-07-22",
    priority = 100,
    source = "asm",
    git_path = "edeneast-nightfox.nvim",
    git_branch = nil,
    color_names = {
      "carbonfox",
      "dawnfox",
      "dayfox",
      "duskfox",
      "nightfox",
      "nordfox",
      "terafox",
    },
  },
  nightfox = {
    handle = "edeneast/nightfox.nvim",
    url = "https://github.com/edeneast/nightfox.nvim",
    github_stars = 2900,
    last_git_commit = "2024-07-22",
    priority = 100,
    source = "asm",
    git_path = "edeneast-nightfox.nvim",
    git_branch = nil,
    color_names = {
      "carbonfox",
      "dawnfox",
      "dayfox",
      "duskfox",
      "nightfox",
      "nordfox",
      "terafox",
    },
  },
  nordfox = {
    handle = "edeneast/nightfox.nvim",
    url = "https://github.com/edeneast/nightfox.nvim",
    github_stars = 2900,
    last_git_commit = "2024-07-22",
    priority = 100,
    source = "asm",
    git_path = "edeneast-nightfox.nvim",
    git_branch = nil,
    color_names = {
      "carbonfox",
      "dawnfox",
      "dayfox",
      "duskfox",
      "nightfox",
      "nordfox",
      "terafox",
    },
  },
  terafox = {
    handle = "edeneast/nightfox.nvim",
    url = "https://github.com/edeneast/nightfox.nvim",
    github_stars = 2900,
    last_git_commit = "2024-07-22",
    priority = 100,
    source = "asm",
    git_path = "edeneast-nightfox.nvim",
    git_branch = nil,
    color_names = {
      "carbonfox",
      "dawnfox",
      "dayfox",
      "duskfox",
      "nightfox",
      "nordfox",
      "terafox",
    },
  },
  everforest = {
    handle = "sainnhe/everforest",
    url = "https://github.com/sainnhe/everforest",
    github_stars = 2700,
    last_git_commit = "2024-07-13",
    priority = 100,
    source = "asm",
    git_path = "sainnhe-everforest",
    git_branch = nil,
    color_names = {
      "everforest",
    },
  },
  PaperColor = {
    handle = "nlknguyen/papercolor-theme",
    url = "https://github.com/nlknguyen/papercolor-theme",
    github_stars = 2666,
    last_git_commit = "2024-03-12",
    priority = 0,
    source = "vsc",
    git_path = "nlknguyen-papercolor-theme",
    git_branch = nil,
    color_names = {
      "PaperColor",
    },
  },
  iceberg = {
    handle = "cocopon/iceberg.vim",
    url = "https://github.com/cocopon/iceberg.vim",
    github_stars = 2177,
    last_git_commit = "2024-06-19",
    priority = 0,
    source = "vsc",
    git_path = "cocopon-iceberg.vim",
    git_branch = nil,
    color_names = {
      "iceberg",
    },
  },
  ["rose-pine"] = {
    handle = "rose-pine/neovim",
    url = "https://github.com/rose-pine/neovim",
    github_stars = 2100,
    last_git_commit = "2024-07-25",
    priority = 100,
    source = "asm",
    git_path = "rose-pine-neovim",
    git_branch = nil,
    color_names = {
      "rose-pine",
      "rose-pine-dawn",
      "rose-pine-main",
      "rose-pine-moon",
    },
  },
  ["rose-pine-dawn"] = {
    handle = "rose-pine/neovim",
    url = "https://github.com/rose-pine/neovim",
    github_stars = 2100,
    last_git_commit = "2024-07-25",
    priority = 100,
    source = "asm",
    git_path = "rose-pine-neovim",
    git_branch = nil,
    color_names = {
      "rose-pine",
      "rose-pine-dawn",
      "rose-pine-main",
      "rose-pine-moon",
    },
  },
  ["rose-pine-main"] = {
    handle = "rose-pine/neovim",
    url = "https://github.com/rose-pine/neovim",
    github_stars = 2100,
    last_git_commit = "2024-07-25",
    priority = 100,
    source = "asm",
    git_path = "rose-pine-neovim",
    git_branch = nil,
    color_names = {
      "rose-pine",
      "rose-pine-dawn",
      "rose-pine-main",
      "rose-pine-moon",
    },
  },
  ["rose-pine-moon"] = {
    handle = "rose-pine/neovim",
    url = "https://github.com/rose-pine/neovim",
    github_stars = 2100,
    last_git_commit = "2024-07-25",
    priority = 100,
    source = "asm",
    git_path = "rose-pine-neovim",
    git_branch = nil,
    color_names = {
      "rose-pine",
      "rose-pine-dawn",
      "rose-pine-main",
      "rose-pine-moon",
    },
  },
  github_dark = {
    handle = "projekt0n/github-nvim-theme",
    url = "https://github.com/projekt0n/github-nvim-theme",
    github_stars = 2000,
    last_git_commit = "2024-07-28",
    priority = 100,
    source = "asm",
    git_path = "projekt0n-github-nvim-theme",
    git_branch = nil,
    color_names = {
      "github_dark",
      "github_dark_colorblind",
      "github_dark_default",
      "github_dark_dimmed",
      "github_dark_high_contrast",
      "github_dark_tritanopia",
      "github_dimmed",
      "github_light",
      "github_light_colorblind",
      "github_light_default",
      "github_light_high_contrast",
      "github_light_tritanopia",
    },
  },
  github_dark_colorblind = {
    handle = "projekt0n/github-nvim-theme",
    url = "https://github.com/projekt0n/github-nvim-theme",
    github_stars = 2000,
    last_git_commit = "2024-07-28",
    priority = 100,
    source = "asm",
    git_path = "projekt0n-github-nvim-theme",
    git_branch = nil,
    color_names = {
      "github_dark",
      "github_dark_colorblind",
      "github_dark_default",
      "github_dark_dimmed",
      "github_dark_high_contrast",
      "github_dark_tritanopia",
      "github_dimmed",
      "github_light",
      "github_light_colorblind",
      "github_light_default",
      "github_light_high_contrast",
      "github_light_tritanopia",
    },
  },
  github_dark_default = {
    handle = "projekt0n/github-nvim-theme",
    url = "https://github.com/projekt0n/github-nvim-theme",
    github_stars = 2000,
    last_git_commit = "2024-07-28",
    priority = 100,
    source = "asm",
    git_path = "projekt0n-github-nvim-theme",
    git_branch = nil,
    color_names = {
      "github_dark",
      "github_dark_colorblind",
      "github_dark_default",
      "github_dark_dimmed",
      "github_dark_high_contrast",
      "github_dark_tritanopia",
      "github_dimmed",
      "github_light",
      "github_light_colorblind",
      "github_light_default",
      "github_light_high_contrast",
      "github_light_tritanopia",
    },
  },
  github_dark_dimmed = {
    handle = "projekt0n/github-nvim-theme",
    url = "https://github.com/projekt0n/github-nvim-theme",
    github_stars = 2000,
    last_git_commit = "2024-07-28",
    priority = 100,
    source = "asm",
    git_path = "projekt0n-github-nvim-theme",
    git_branch = nil,
    color_names = {
      "github_dark",
      "github_dark_colorblind",
      "github_dark_default",
      "github_dark_dimmed",
      "github_dark_high_contrast",
      "github_dark_tritanopia",
      "github_dimmed",
      "github_light",
      "github_light_colorblind",
      "github_light_default",
      "github_light_high_contrast",
      "github_light_tritanopia",
    },
  },
  github_dark_high_contrast = {
    handle = "projekt0n/github-nvim-theme",
    url = "https://github.com/projekt0n/github-nvim-theme",
    github_stars = 2000,
    last_git_commit = "2024-07-28",
    priority = 100,
    source = "asm",
    git_path = "projekt0n-github-nvim-theme",
    git_branch = nil,
    color_names = {
      "github_dark",
      "github_dark_colorblind",
      "github_dark_default",
      "github_dark_dimmed",
      "github_dark_high_contrast",
      "github_dark_tritanopia",
      "github_dimmed",
      "github_light",
      "github_light_colorblind",
      "github_light_default",
      "github_light_high_contrast",
      "github_light_tritanopia",
    },
  },
  github_dark_tritanopia = {
    handle = "projekt0n/github-nvim-theme",
    url = "https://github.com/projekt0n/github-nvim-theme",
    github_stars = 2000,
    last_git_commit = "2024-07-28",
    priority = 100,
    source = "asm",
    git_path = "projekt0n-github-nvim-theme",
    git_branch = nil,
    color_names = {
      "github_dark",
      "github_dark_colorblind",
      "github_dark_default",
      "github_dark_dimmed",
      "github_dark_high_contrast",
      "github_dark_tritanopia",
      "github_dimmed",
      "github_light",
      "github_light_colorblind",
      "github_light_default",
      "github_light_high_contrast",
      "github_light_tritanopia",
    },
  },
  github_dimmed = {
    handle = "projekt0n/github-nvim-theme",
    url = "https://github.com/projekt0n/github-nvim-theme",
    github_stars = 2000,
    last_git_commit = "2024-07-28",
    priority = 100,
    source = "asm",
    git_path = "projekt0n-github-nvim-theme",
    git_branch = nil,
    color_names = {
      "github_dark",
      "github_dark_colorblind",
      "github_dark_default",
      "github_dark_dimmed",
      "github_dark_high_contrast",
      "github_dark_tritanopia",
      "github_dimmed",
      "github_light",
      "github_light_colorblind",
      "github_light_default",
      "github_light_high_contrast",
      "github_light_tritanopia",
    },
  },
  github_light = {
    handle = "projekt0n/github-nvim-theme",
    url = "https://github.com/projekt0n/github-nvim-theme",
    github_stars = 2000,
    last_git_commit = "2024-07-28",
    priority = 100,
    source = "asm",
    git_path = "projekt0n-github-nvim-theme",
    git_branch = nil,
    color_names = {
      "github_dark",
      "github_dark_colorblind",
      "github_dark_default",
      "github_dark_dimmed",
      "github_dark_high_contrast",
      "github_dark_tritanopia",
      "github_dimmed",
      "github_light",
      "github_light_colorblind",
      "github_light_default",
      "github_light_high_contrast",
      "github_light_tritanopia",
    },
  },
  github_light_colorblind = {
    handle = "projekt0n/github-nvim-theme",
    url = "https://github.com/projekt0n/github-nvim-theme",
    github_stars = 2000,
    last_git_commit = "2024-07-28",
    priority = 100,
    source = "asm",
    git_path = "projekt0n-github-nvim-theme",
    git_branch = nil,
    color_names = {
      "github_dark",
      "github_dark_colorblind",
      "github_dark_default",
      "github_dark_dimmed",
      "github_dark_high_contrast",
      "github_dark_tritanopia",
      "github_dimmed",
      "github_light",
      "github_light_colorblind",
      "github_light_default",
      "github_light_high_contrast",
      "github_light_tritanopia",
    },
  },
  github_light_default = {
    handle = "projekt0n/github-nvim-theme",
    url = "https://github.com/projekt0n/github-nvim-theme",
    github_stars = 2000,
    last_git_commit = "2024-07-28",
    priority = 100,
    source = "asm",
    git_path = "projekt0n-github-nvim-theme",
    git_branch = nil,
    color_names = {
      "github_dark",
      "github_dark_colorblind",
      "github_dark_default",
      "github_dark_dimmed",
      "github_dark_high_contrast",
      "github_dark_tritanopia",
      "github_dimmed",
      "github_light",
      "github_light_colorblind",
      "github_light_default",
      "github_light_high_contrast",
      "github_light_tritanopia",
    },
  },
  github_light_high_contrast = {
    handle = "projekt0n/github-nvim-theme",
    url = "https://github.com/projekt0n/github-nvim-theme",
    github_stars = 2000,
    last_git_commit = "2024-07-28",
    priority = 100,
    source = "asm",
    git_path = "projekt0n-github-nvim-theme",
    git_branch = nil,
    color_names = {
      "github_dark",
      "github_dark_colorblind",
      "github_dark_default",
      "github_dark_dimmed",
      "github_dark_high_contrast",
      "github_dark_tritanopia",
      "github_dimmed",
      "github_light",
      "github_light_colorblind",
      "github_light_default",
      "github_light_high_contrast",
      "github_light_tritanopia",
    },
  },
  github_light_tritanopia = {
    handle = "projekt0n/github-nvim-theme",
    url = "https://github.com/projekt0n/github-nvim-theme",
    github_stars = 2000,
    last_git_commit = "2024-07-28",
    priority = 100,
    source = "asm",
    git_path = "projekt0n-github-nvim-theme",
    git_branch = nil,
    color_names = {
      "github_dark",
      "github_dark_colorblind",
      "github_dark_default",
      "github_dark_dimmed",
      "github_dark_high_contrast",
      "github_dark_tritanopia",
      "github_dimmed",
      "github_light",
      "github_light_colorblind",
      "github_light_default",
      "github_light_high_contrast",
      "github_light_tritanopia",
    },
  },
  one = {
    handle = "rakr/vim-one",
    url = "https://github.com/rakr/vim-one",
    github_stars = 1981,
    last_git_commit = "2020-12-14",
    priority = 0,
    source = "vsc",
    git_path = "rakr-vim-one",
    git_branch = nil,
    color_names = {
      "one",
    },
  },
  ["gruvbox-material"] = {
    handle = "sainnhe/gruvbox-material",
    url = "https://github.com/sainnhe/gruvbox-material",
    github_stars = 1800,
    last_git_commit = "2024-07-13",
    priority = 100,
    source = "asm",
    git_path = "sainnhe-gruvbox-material",
    git_branch = nil,
    color_names = {
      "gruvbox-material",
    },
  },
  gruvbox = {
    handle = "ellisonleao/gruvbox.nvim",
    url = "https://github.com/ellisonleao/gruvbox.nvim",
    github_stars = 1800,
    last_git_commit = "2024-07-04",
    priority = 100,
    source = "asm",
    git_path = "ellisonleao-gruvbox.nvim",
    git_branch = nil,
    color_names = {
      "gruvbox",
    },
  },
  ayu = {
    handle = "ayu-theme/ayu-vim",
    url = "https://github.com/ayu-theme/ayu-vim",
    github_stars = 1659,
    last_git_commit = "2024-07-15",
    priority = 0,
    source = "vsc",
    git_path = "ayu-theme-ayu-vim",
    git_branch = nil,
    color_names = {
      "ayu",
    },
  },
  seoul256 = {
    handle = "junegunn/seoul256.vim",
    url = "https://github.com/junegunn/seoul256.vim",
    github_stars = 1637,
    last_git_commit = "2023-05-03",
    priority = 0,
    source = "vsc",
    git_path = "junegunn-seoul256.vim",
    git_branch = nil,
    color_names = {
      "seoul256",
      "seoul256-light",
    },
  },
  ["seoul256-light"] = {
    handle = "junegunn/seoul256.vim",
    url = "https://github.com/junegunn/seoul256.vim",
    github_stars = 1637,
    last_git_commit = "2023-05-03",
    priority = 0,
    source = "vsc",
    git_path = "junegunn-seoul256.vim",
    git_branch = nil,
    color_names = {
      "seoul256",
      "seoul256-light",
    },
  },
  sonokai = {
    handle = "sainnhe/sonokai",
    url = "https://github.com/sainnhe/sonokai",
    github_stars = 1600,
    last_git_commit = "2024-07-13",
    priority = 100,
    source = "asm",
    git_path = "sainnhe-sonokai",
    git_branch = nil,
    color_names = {
      "sonokai",
    },
  },
  onedark = {
    handle = "navarasu/onedark.nvim",
    url = "https://github.com/navarasu/onedark.nvim",
    github_stars = 1500,
    last_git_commit = "2024-07-05",
    priority = 100,
    source = "asm",
    git_path = "navarasu-onedark.nvim",
    git_branch = nil,
    color_names = {
      "onedark",
    },
  },
  monokai = {
    handle = "ku1ik/vim-monokai",
    url = "https://github.com/ku1ik/vim-monokai",
    github_stars = 1429,
    last_git_commit = "2022-02-09",
    priority = 0,
    source = "vsc",
    git_path = "ku1ik-vim-monokai",
    git_branch = nil,
    color_names = {
      "monokai",
    },
  },
  dracula = {
    handle = "dracula/vim",
    url = "https://github.com/dracula/vim",
    github_stars = 1300,
    last_git_commit = "2024-07-21",
    priority = 100,
    source = "asm",
    git_path = "dracula-vim",
    git_branch = nil,
    color_names = {
      "dracula",
    },
  },
  badwolf = {
    handle = "sjl/badwolf",
    url = "https://github.com/sjl/badwolf",
    github_stars = 1245,
    last_git_commit = "2024-05-23",
    priority = 0,
    source = "vsc",
    git_path = "sjl-badwolf",
    git_branch = nil,
    color_names = {
      "badwolf",
      "goodwolf",
    },
  },
  goodwolf = {
    handle = "sjl/badwolf",
    url = "https://github.com/sjl/badwolf",
    github_stars = 1245,
    last_git_commit = "2024-05-23",
    priority = 0,
    source = "vsc",
    git_path = "sjl-badwolf",
    git_branch = nil,
    color_names = {
      "badwolf",
      "goodwolf",
    },
  },
  gotham = {
    handle = "whatyouhide/vim-gotham",
    url = "https://github.com/whatyouhide/vim-gotham",
    github_stars = 1237,
    last_git_commit = "2023-01-19",
    priority = 0,
    source = "vsc",
    git_path = "whatyouhide-vim-gotham",
    git_branch = nil,
    color_names = {
      "gotham",
      "gotham256",
    },
  },
  gotham256 = {
    handle = "whatyouhide/vim-gotham",
    url = "https://github.com/whatyouhide/vim-gotham",
    github_stars = 1237,
    last_git_commit = "2023-01-19",
    priority = 0,
    source = "vsc",
    git_path = "whatyouhide-vim-gotham",
    git_branch = nil,
    color_names = {
      "gotham",
      "gotham256",
    },
  },
  tender = {
    handle = "jacoborus/tender.vim",
    url = "https://github.com/jacoborus/tender.vim",
    github_stars = 1124,
    last_git_commit = "2024-04-21",
    priority = 0,
    source = "vsc",
    git_path = "jacoborus-tender.vim",
    git_branch = nil,
    color_names = {
      "tender",
    },
  },
  OceanicNext = {
    handle = "mhartington/oceanic-next",
    url = "https://github.com/mhartington/oceanic-next",
    github_stars = 1100,
    last_git_commit = "2023-05-01",
    priority = 100,
    source = "asm",
    git_path = "mhartington-oceanic-next",
    git_branch = nil,
    color_names = {
      "OceanicNext",
      "OceanicNextLight",
    },
  },
  OceanicNextLight = {
    handle = "mhartington/oceanic-next",
    url = "https://github.com/mhartington/oceanic-next",
    github_stars = 1100,
    last_git_commit = "2023-05-01",
    priority = 100,
    source = "asm",
    git_path = "mhartington-oceanic-next",
    git_branch = nil,
    color_names = {
      "OceanicNext",
      "OceanicNextLight",
    },
  },
  oxocarbon = {
    handle = "nyoom-engineering/oxocarbon.nvim",
    url = "https://github.com/nyoom-engineering/oxocarbon.nvim",
    github_stars = 1000,
    last_git_commit = "2023-11-27",
    priority = 100,
    source = "asm",
    git_path = "nyoom-engineering-oxocarbon.nvim",
    git_branch = nil,
    color_names = {
      "oxocarbon",
    },
  },
  solarized8 = {
    handle = "lifepillar/vim-solarized8",
    url = "https://github.com/lifepillar/vim-solarized8",
    github_stars = 1000,
    last_git_commit = "2024-05-21",
    priority = 0,
    source = "vsc",
    git_path = "lifepillar-vim-solarized8",
    git_branch = "neovim",
    color_names = {
      "solarized8",
      "solarized8_flat",
      "solarized8_high",
      "solarized8_low",
    },
  },
  solarized8_flat = {
    handle = "lifepillar/vim-solarized8",
    url = "https://github.com/lifepillar/vim-solarized8",
    github_stars = 1000,
    last_git_commit = "2024-05-21",
    priority = 0,
    source = "vsc",
    git_path = "lifepillar-vim-solarized8",
    git_branch = "neovim",
    color_names = {
      "solarized8",
      "solarized8_flat",
      "solarized8_high",
      "solarized8_low",
    },
  },
  solarized8_high = {
    handle = "lifepillar/vim-solarized8",
    url = "https://github.com/lifepillar/vim-solarized8",
    github_stars = 1000,
    last_git_commit = "2024-05-21",
    priority = 0,
    source = "vsc",
    git_path = "lifepillar-vim-solarized8",
    git_branch = "neovim",
    color_names = {
      "solarized8",
      "solarized8_flat",
      "solarized8_high",
      "solarized8_low",
    },
  },
  solarized8_low = {
    handle = "lifepillar/vim-solarized8",
    url = "https://github.com/lifepillar/vim-solarized8",
    github_stars = 1000,
    last_git_commit = "2024-05-21",
    priority = 0,
    source = "vsc",
    git_path = "lifepillar-vim-solarized8",
    git_branch = "neovim",
    color_names = {
      "solarized8",
      "solarized8_flat",
      "solarized8_high",
      "solarized8_low",
    },
  },
  material = {
    handle = "marko-cerovac/material.nvim",
    url = "https://github.com/marko-cerovac/material.nvim",
    github_stars = 954,
    last_git_commit = "2024-06-26",
    priority = 100,
    source = "asm",
    git_path = "marko-cerovac-material.nvim",
    git_branch = nil,
    color_names = {
      "material",
      "material-darker",
      "material-deep-ocean",
      "material-lighter",
      "material-oceanic",
      "material-palenight",
    },
  },
  ["material-darker"] = {
    handle = "marko-cerovac/material.nvim",
    url = "https://github.com/marko-cerovac/material.nvim",
    github_stars = 954,
    last_git_commit = "2024-06-26",
    priority = 100,
    source = "asm",
    git_path = "marko-cerovac-material.nvim",
    git_branch = nil,
    color_names = {
      "material",
      "material-darker",
      "material-deep-ocean",
      "material-lighter",
      "material-oceanic",
      "material-palenight",
    },
  },
  ["material-deep-ocean"] = {
    handle = "marko-cerovac/material.nvim",
    url = "https://github.com/marko-cerovac/material.nvim",
    github_stars = 954,
    last_git_commit = "2024-06-26",
    priority = 100,
    source = "asm",
    git_path = "marko-cerovac-material.nvim",
    git_branch = nil,
    color_names = {
      "material",
      "material-darker",
      "material-deep-ocean",
      "material-lighter",
      "material-oceanic",
      "material-palenight",
    },
  },
  ["material-lighter"] = {
    handle = "marko-cerovac/material.nvim",
    url = "https://github.com/marko-cerovac/material.nvim",
    github_stars = 954,
    last_git_commit = "2024-06-26",
    priority = 100,
    source = "asm",
    git_path = "marko-cerovac-material.nvim",
    git_branch = nil,
    color_names = {
      "material",
      "material-darker",
      "material-deep-ocean",
      "material-lighter",
      "material-oceanic",
      "material-palenight",
    },
  },
  ["material-oceanic"] = {
    handle = "marko-cerovac/material.nvim",
    url = "https://github.com/marko-cerovac/material.nvim",
    github_stars = 954,
    last_git_commit = "2024-06-26",
    priority = 100,
    source = "asm",
    git_path = "marko-cerovac-material.nvim",
    git_branch = nil,
    color_names = {
      "material",
      "material-darker",
      "material-deep-ocean",
      "material-lighter",
      "material-oceanic",
      "material-palenight",
    },
  },
  ["material-palenight"] = {
    handle = "marko-cerovac/material.nvim",
    url = "https://github.com/marko-cerovac/material.nvim",
    github_stars = 954,
    last_git_commit = "2024-06-26",
    priority = 100,
    source = "asm",
    git_path = "marko-cerovac-material.nvim",
    git_branch = nil,
    color_names = {
      "material",
      "material-darker",
      "material-deep-ocean",
      "material-lighter",
      "material-oceanic",
      "material-palenight",
    },
  },
  codedark = {
    handle = "tomasiser/vim-code-dark",
    url = "https://github.com/tomasiser/vim-code-dark",
    github_stars = 930,
    last_git_commit = "2024-05-21",
    priority = 100,
    source = "asm",
    git_path = "tomasiser-vim-code-dark",
    git_branch = nil,
    color_names = {
      "codedark",
    },
  },
  zenburn = {
    handle = "jnurmine/zenburn",
    url = "https://github.com/jnurmine/zenburn",
    github_stars = 888,
    last_git_commit = "2022-08-08",
    priority = 0,
    source = "vsc",
    git_path = "jnurmine-zenburn",
    git_branch = nil,
    color_names = {
      "zenburn",
    },
  },
  apprentice = {
    handle = "romainl/apprentice",
    url = "https://github.com/romainl/apprentice",
    github_stars = 874,
    last_git_commit = "2023-02-15",
    priority = 0,
    source = "vsc",
    git_path = "romainl-apprentice",
    git_branch = nil,
    color_names = {
      "apprentice",
    },
  },
  edge = {
    handle = "sainnhe/edge",
    url = "https://github.com/sainnhe/edge",
    github_stars = 850,
    last_git_commit = "2024-07-13",
    priority = 100,
    source = "asm",
    git_path = "sainnhe-edge",
    git_branch = nil,
    color_names = {
      "edge",
    },
  },
  srcery = {
    handle = "srcery-colors/srcery-vim",
    url = "https://github.com/srcery-colors/srcery-vim",
    github_stars = 811,
    last_git_commit = "2024-05-30",
    priority = 0,
    source = "vsc",
    git_path = "srcery-colors-srcery-vim",
    git_branch = nil,
    color_names = {
      "srcery",
    },
  },
  spaceduck = {
    handle = "pineapplegiant/spaceduck",
    url = "https://github.com/pineapplegiant/spaceduck",
    github_stars = 797,
    last_git_commit = "2022-02-21",
    priority = 0,
    source = "vsc",
    git_path = "pineapplegiant-spaceduck",
    git_branch = nil,
    color_names = {
      "spaceduck",
    },
  },
  lucario = {
    handle = "raphamorim/lucario",
    url = "https://github.com/raphamorim/lucario",
    github_stars = 791,
    last_git_commit = "2024-06-23",
    priority = 0,
    source = "vsc",
    git_path = "raphamorim-lucario",
    git_branch = nil,
    color_names = {
      "lucario",
    },
  },
  moonfly = {
    handle = "bluz71/vim-moonfly-colors",
    url = "https://github.com/bluz71/vim-moonfly-colors",
    github_stars = 788,
    last_git_commit = "2024-07-25",
    priority = 100,
    source = "asm",
    git_path = "bluz71-vim-moonfly-colors",
    git_branch = nil,
    color_names = {
      "moonfly",
    },
  },
  nord = {
    handle = "shaunsingh/nord.nvim",
    url = "https://github.com/shaunsingh/nord.nvim",
    github_stars = 783,
    last_git_commit = "2023-12-20",
    priority = 100,
    source = "asm",
    git_path = "shaunsingh-nord.nvim",
    git_branch = nil,
    color_names = {
      "nord",
    },
  },
  nightfly = {
    handle = "bluz71/vim-nightfly-colors",
    url = "https://github.com/bluz71/vim-nightfly-colors",
    github_stars = 779,
    last_git_commit = "2024-07-25",
    priority = 100,
    source = "asm",
    git_path = "bluz71-vim-nightfly-colors",
    git_branch = nil,
    color_names = {
      "nightfly",
    },
  },
  deus = {
    handle = "ajmwagar/vim-deus",
    url = "https://github.com/ajmwagar/vim-deus",
    github_stars = 763,
    last_git_commit = "2021-03-28",
    priority = 0,
    source = "vsc",
    git_path = "ajmwagar-vim-deus",
    git_branch = nil,
    color_names = {
      "deus",
    },
  },
  falcon = {
    handle = "fenetikm/falcon",
    url = "https://github.com/fenetikm/falcon",
    github_stars = 715,
    last_git_commit = "2023-03-12",
    priority = 100,
    source = "asm",
    git_path = "fenetikm-falcon",
    git_branch = nil,
    color_names = {
      "falcon",
    },
  },
  melange = {
    handle = "savq/melange-nvim",
    url = "https://github.com/savq/melange-nvim",
    github_stars = 673,
    last_git_commit = "2024-06-29",
    priority = 100,
    source = "asm",
    git_path = "savq-melange-nvim",
    git_branch = nil,
    color_names = {
      "melange",
    },
  },
  vscode = {
    handle = "mofiqul/vscode.nvim",
    url = "https://github.com/mofiqul/vscode.nvim",
    github_stars = 663,
    last_git_commit = "2024-07-28",
    priority = 100,
    source = "asm",
    git_path = "mofiqul-vscode.nvim",
    git_branch = nil,
    color_names = {
      "vscode",
    },
  },
  palenight = {
    handle = "drewtempelmeyer/palenight.vim",
    url = "https://github.com/drewtempelmeyer/palenight.vim",
    github_stars = 655,
    last_git_commit = "2023-04-27",
    priority = 0,
    source = "vsc",
    git_path = "drewtempelmeyer-palenight.vim",
    git_branch = nil,
    color_names = {
      "palenight",
    },
  },
  duckbones = {
    handle = "mcchrish/zenbones.nvim",
    url = "https://github.com/mcchrish/zenbones.nvim",
    github_stars = 655,
    last_git_commit = "2024-06-16",
    priority = 100,
    source = "asm",
    git_path = "mcchrish-zenbones.nvim",
    git_branch = nil,
    color_names = {
      "duckbones",
      "forestbones",
      "kanagawabones",
      "neobones",
      "nordbones",
      "randombones",
      "rosebones",
      "seoulbones",
      "tokyobones",
      "vimbones",
      "zenbones",
      "zenburned",
      "zenwritten",
    },
  },
  forestbones = {
    handle = "mcchrish/zenbones.nvim",
    url = "https://github.com/mcchrish/zenbones.nvim",
    github_stars = 655,
    last_git_commit = "2024-06-16",
    priority = 100,
    source = "asm",
    git_path = "mcchrish-zenbones.nvim",
    git_branch = nil,
    color_names = {
      "duckbones",
      "forestbones",
      "kanagawabones",
      "neobones",
      "nordbones",
      "randombones",
      "rosebones",
      "seoulbones",
      "tokyobones",
      "vimbones",
      "zenbones",
      "zenburned",
      "zenwritten",
    },
  },
  kanagawabones = {
    handle = "mcchrish/zenbones.nvim",
    url = "https://github.com/mcchrish/zenbones.nvim",
    github_stars = 655,
    last_git_commit = "2024-06-16",
    priority = 100,
    source = "asm",
    git_path = "mcchrish-zenbones.nvim",
    git_branch = nil,
    color_names = {
      "duckbones",
      "forestbones",
      "kanagawabones",
      "neobones",
      "nordbones",
      "randombones",
      "rosebones",
      "seoulbones",
      "tokyobones",
      "vimbones",
      "zenbones",
      "zenburned",
      "zenwritten",
    },
  },
  neobones = {
    handle = "mcchrish/zenbones.nvim",
    url = "https://github.com/mcchrish/zenbones.nvim",
    github_stars = 655,
    last_git_commit = "2024-06-16",
    priority = 100,
    source = "asm",
    git_path = "mcchrish-zenbones.nvim",
    git_branch = nil,
    color_names = {
      "duckbones",
      "forestbones",
      "kanagawabones",
      "neobones",
      "nordbones",
      "randombones",
      "rosebones",
      "seoulbones",
      "tokyobones",
      "vimbones",
      "zenbones",
      "zenburned",
      "zenwritten",
    },
  },
  nordbones = {
    handle = "mcchrish/zenbones.nvim",
    url = "https://github.com/mcchrish/zenbones.nvim",
    github_stars = 655,
    last_git_commit = "2024-06-16",
    priority = 100,
    source = "asm",
    git_path = "mcchrish-zenbones.nvim",
    git_branch = nil,
    color_names = {
      "duckbones",
      "forestbones",
      "kanagawabones",
      "neobones",
      "nordbones",
      "randombones",
      "rosebones",
      "seoulbones",
      "tokyobones",
      "vimbones",
      "zenbones",
      "zenburned",
      "zenwritten",
    },
  },
  randombones = {
    handle = "mcchrish/zenbones.nvim",
    url = "https://github.com/mcchrish/zenbones.nvim",
    github_stars = 655,
    last_git_commit = "2024-06-16",
    priority = 100,
    source = "asm",
    git_path = "mcchrish-zenbones.nvim",
    git_branch = nil,
    color_names = {
      "duckbones",
      "forestbones",
      "kanagawabones",
      "neobones",
      "nordbones",
      "randombones",
      "rosebones",
      "seoulbones",
      "tokyobones",
      "vimbones",
      "zenbones",
      "zenburned",
      "zenwritten",
    },
  },
  rosebones = {
    handle = "mcchrish/zenbones.nvim",
    url = "https://github.com/mcchrish/zenbones.nvim",
    github_stars = 655,
    last_git_commit = "2024-06-16",
    priority = 100,
    source = "asm",
    git_path = "mcchrish-zenbones.nvim",
    git_branch = nil,
    color_names = {
      "duckbones",
      "forestbones",
      "kanagawabones",
      "neobones",
      "nordbones",
      "randombones",
      "rosebones",
      "seoulbones",
      "tokyobones",
      "vimbones",
      "zenbones",
      "zenburned",
      "zenwritten",
    },
  },
  seoulbones = {
    handle = "mcchrish/zenbones.nvim",
    url = "https://github.com/mcchrish/zenbones.nvim",
    github_stars = 655,
    last_git_commit = "2024-06-16",
    priority = 100,
    source = "asm",
    git_path = "mcchrish-zenbones.nvim",
    git_branch = nil,
    color_names = {
      "duckbones",
      "forestbones",
      "kanagawabones",
      "neobones",
      "nordbones",
      "randombones",
      "rosebones",
      "seoulbones",
      "tokyobones",
      "vimbones",
      "zenbones",
      "zenburned",
      "zenwritten",
    },
  },
  tokyobones = {
    handle = "mcchrish/zenbones.nvim",
    url = "https://github.com/mcchrish/zenbones.nvim",
    github_stars = 655,
    last_git_commit = "2024-06-16",
    priority = 100,
    source = "asm",
    git_path = "mcchrish-zenbones.nvim",
    git_branch = nil,
    color_names = {
      "duckbones",
      "forestbones",
      "kanagawabones",
      "neobones",
      "nordbones",
      "randombones",
      "rosebones",
      "seoulbones",
      "tokyobones",
      "vimbones",
      "zenbones",
      "zenburned",
      "zenwritten",
    },
  },
  vimbones = {
    handle = "mcchrish/zenbones.nvim",
    url = "https://github.com/mcchrish/zenbones.nvim",
    github_stars = 655,
    last_git_commit = "2024-06-16",
    priority = 100,
    source = "asm",
    git_path = "mcchrish-zenbones.nvim",
    git_branch = nil,
    color_names = {
      "duckbones",
      "forestbones",
      "kanagawabones",
      "neobones",
      "nordbones",
      "randombones",
      "rosebones",
      "seoulbones",
      "tokyobones",
      "vimbones",
      "zenbones",
      "zenburned",
      "zenwritten",
    },
  },
  zenbones = {
    handle = "mcchrish/zenbones.nvim",
    url = "https://github.com/mcchrish/zenbones.nvim",
    github_stars = 655,
    last_git_commit = "2024-06-16",
    priority = 100,
    source = "asm",
    git_path = "mcchrish-zenbones.nvim",
    git_branch = nil,
    color_names = {
      "duckbones",
      "forestbones",
      "kanagawabones",
      "neobones",
      "nordbones",
      "randombones",
      "rosebones",
      "seoulbones",
      "tokyobones",
      "vimbones",
      "zenbones",
      "zenburned",
      "zenwritten",
    },
  },
  zenburned = {
    handle = "mcchrish/zenbones.nvim",
    url = "https://github.com/mcchrish/zenbones.nvim",
    github_stars = 655,
    last_git_commit = "2024-06-16",
    priority = 100,
    source = "asm",
    git_path = "mcchrish-zenbones.nvim",
    git_branch = nil,
    color_names = {
      "duckbones",
      "forestbones",
      "kanagawabones",
      "neobones",
      "nordbones",
      "randombones",
      "rosebones",
      "seoulbones",
      "tokyobones",
      "vimbones",
      "zenbones",
      "zenburned",
      "zenwritten",
    },
  },
  zenwritten = {
    handle = "mcchrish/zenbones.nvim",
    url = "https://github.com/mcchrish/zenbones.nvim",
    github_stars = 655,
    last_git_commit = "2024-06-16",
    priority = 100,
    source = "asm",
    git_path = "mcchrish-zenbones.nvim",
    git_branch = nil,
    color_names = {
      "duckbones",
      "forestbones",
      "kanagawabones",
      "neobones",
      "nordbones",
      "randombones",
      "rosebones",
      "seoulbones",
      "tokyobones",
      "vimbones",
      "zenbones",
      "zenburned",
      "zenwritten",
    },
  },
  embark = {
    handle = "embark-theme/vim",
    url = "https://github.com/embark-theme/vim",
    github_stars = 644,
    last_git_commit = "2024-06-25",
    priority = 100,
    source = "asm",
    git_path = "embark-theme-vim",
    git_branch = nil,
    color_names = {
      "embark",
    },
  },
  nordic = {
    handle = "alexvzyl/nordic.nvim",
    url = "https://github.com/alexvzyl/nordic.nvim",
    github_stars = 642,
    last_git_commit = "2024-04-14",
    priority = 100,
    source = "asm",
    git_path = "alexvzyl-nordic.nvim",
    git_branch = nil,
    color_names = {
      "nordic",
    },
  },
  colorbuddy = {
    handle = "tjdevries/colorbuddy.nvim",
    url = "https://github.com/tjdevries/colorbuddy.nvim",
    github_stars = 630,
    last_git_commit = "2024-05-08",
    priority = 0,
    source = "vsc",
    git_path = "tjdevries-colorbuddy.nvim",
    git_branch = nil,
    color_names = {
      "colorbuddy",
      "gruvbuddy",
    },
  },
  gruvbuddy = {
    handle = "tjdevries/colorbuddy.nvim",
    url = "https://github.com/tjdevries/colorbuddy.nvim",
    github_stars = 630,
    last_git_commit = "2024-05-08",
    priority = 0,
    source = "vsc",
    git_path = "tjdevries-colorbuddy.nvim",
    git_branch = nil,
    color_names = {
      "colorbuddy",
      "gruvbuddy",
    },
  },
  pencil = {
    handle = "preservim/vim-colors-pencil",
    url = "https://github.com/preservim/vim-colors-pencil",
    github_stars = 604,
    last_git_commit = "2022-05-07",
    priority = 0,
    source = "vsc",
    git_path = "preservim-vim-colors-pencil",
    git_branch = nil,
    color_names = {
      "pencil",
    },
  },
  ["solarized-osaka"] = {
    handle = "craftzdog/solarized-osaka.nvim",
    url = "https://github.com/craftzdog/solarized-osaka.nvim",
    github_stars = 600,
    last_git_commit = "2024-07-03",
    priority = 0,
    source = "vsc",
    git_path = "craftzdog-solarized-osaka.nvim",
    git_branch = nil,
    color_names = {
      "solarized-osaka",
      "solarized-osaka-day",
      "solarized-osaka-moon",
      "solarized-osaka-night",
      "solarized-osaka-storm",
    },
  },
  ["solarized-osaka-day"] = {
    handle = "craftzdog/solarized-osaka.nvim",
    url = "https://github.com/craftzdog/solarized-osaka.nvim",
    github_stars = 600,
    last_git_commit = "2024-07-03",
    priority = 0,
    source = "vsc",
    git_path = "craftzdog-solarized-osaka.nvim",
    git_branch = nil,
    color_names = {
      "solarized-osaka",
      "solarized-osaka-day",
      "solarized-osaka-moon",
      "solarized-osaka-night",
      "solarized-osaka-storm",
    },
  },
  ["solarized-osaka-moon"] = {
    handle = "craftzdog/solarized-osaka.nvim",
    url = "https://github.com/craftzdog/solarized-osaka.nvim",
    github_stars = 600,
    last_git_commit = "2024-07-03",
    priority = 0,
    source = "vsc",
    git_path = "craftzdog-solarized-osaka.nvim",
    git_branch = nil,
    color_names = {
      "solarized-osaka",
      "solarized-osaka-day",
      "solarized-osaka-moon",
      "solarized-osaka-night",
      "solarized-osaka-storm",
    },
  },
  ["solarized-osaka-night"] = {
    handle = "craftzdog/solarized-osaka.nvim",
    url = "https://github.com/craftzdog/solarized-osaka.nvim",
    github_stars = 600,
    last_git_commit = "2024-07-03",
    priority = 0,
    source = "vsc",
    git_path = "craftzdog-solarized-osaka.nvim",
    git_branch = nil,
    color_names = {
      "solarized-osaka",
      "solarized-osaka-day",
      "solarized-osaka-moon",
      "solarized-osaka-night",
      "solarized-osaka-storm",
    },
  },
  ["solarized-osaka-storm"] = {
    handle = "craftzdog/solarized-osaka.nvim",
    url = "https://github.com/craftzdog/solarized-osaka.nvim",
    github_stars = 600,
    last_git_commit = "2024-07-03",
    priority = 0,
    source = "vsc",
    git_path = "craftzdog-solarized-osaka.nvim",
    git_branch = nil,
    color_names = {
      "solarized-osaka",
      "solarized-osaka-day",
      "solarized-osaka-moon",
      "solarized-osaka-night",
      "solarized-osaka-storm",
    },
  },
  ["space-vim-dark"] = {
    handle = "liuchengxu/space-vim-dark",
    url = "https://github.com/liuchengxu/space-vim-dark",
    github_stars = 590,
    last_git_commit = "2023-11-04",
    priority = 0,
    source = "vsc",
    git_path = "liuchengxu-space-vim-dark",
    git_branch = nil,
    color_names = {
      "space-vim-dark",
    },
  },
  challenger_deep = {
    handle = "challenger-deep-theme/vim",
    url = "https://github.com/challenger-deep-theme/vim",
    github_stars = 585,
    last_git_commit = "2022-04-25",
    priority = 0,
    source = "vsc",
    git_path = "challenger-deep-theme-vim",
    git_branch = nil,
    color_names = {
      "challenger_deep",
    },
  },
  xcode = {
    handle = "lunacookies/vim-colors-xcode",
    url = "https://github.com/lunacookies/vim-colors-xcode",
    github_stars = 581,
    last_git_commit = "2023-11-06",
    priority = 0,
    source = "vsc",
    git_path = "lunacookies-vim-colors-xcode",
    git_branch = nil,
    color_names = {
      "xcode",
      "xcodedark",
      "xcodedarkhc",
      "xcodehc",
      "xcodelight",
      "xcodelighthc",
      "xcodewwdc",
    },
  },
  xcodedark = {
    handle = "lunacookies/vim-colors-xcode",
    url = "https://github.com/lunacookies/vim-colors-xcode",
    github_stars = 581,
    last_git_commit = "2023-11-06",
    priority = 0,
    source = "vsc",
    git_path = "lunacookies-vim-colors-xcode",
    git_branch = nil,
    color_names = {
      "xcode",
      "xcodedark",
      "xcodedarkhc",
      "xcodehc",
      "xcodelight",
      "xcodelighthc",
      "xcodewwdc",
    },
  },
  xcodedarkhc = {
    handle = "lunacookies/vim-colors-xcode",
    url = "https://github.com/lunacookies/vim-colors-xcode",
    github_stars = 581,
    last_git_commit = "2023-11-06",
    priority = 0,
    source = "vsc",
    git_path = "lunacookies-vim-colors-xcode",
    git_branch = nil,
    color_names = {
      "xcode",
      "xcodedark",
      "xcodedarkhc",
      "xcodehc",
      "xcodelight",
      "xcodelighthc",
      "xcodewwdc",
    },
  },
  xcodehc = {
    handle = "lunacookies/vim-colors-xcode",
    url = "https://github.com/lunacookies/vim-colors-xcode",
    github_stars = 581,
    last_git_commit = "2023-11-06",
    priority = 0,
    source = "vsc",
    git_path = "lunacookies-vim-colors-xcode",
    git_branch = nil,
    color_names = {
      "xcode",
      "xcodedark",
      "xcodedarkhc",
      "xcodehc",
      "xcodelight",
      "xcodelighthc",
      "xcodewwdc",
    },
  },
  xcodelight = {
    handle = "lunacookies/vim-colors-xcode",
    url = "https://github.com/lunacookies/vim-colors-xcode",
    github_stars = 581,
    last_git_commit = "2023-11-06",
    priority = 0,
    source = "vsc",
    git_path = "lunacookies-vim-colors-xcode",
    git_branch = nil,
    color_names = {
      "xcode",
      "xcodedark",
      "xcodedarkhc",
      "xcodehc",
      "xcodelight",
      "xcodelighthc",
      "xcodewwdc",
    },
  },
  xcodelighthc = {
    handle = "lunacookies/vim-colors-xcode",
    url = "https://github.com/lunacookies/vim-colors-xcode",
    github_stars = 581,
    last_git_commit = "2023-11-06",
    priority = 0,
    source = "vsc",
    git_path = "lunacookies-vim-colors-xcode",
    git_branch = nil,
    color_names = {
      "xcode",
      "xcodedark",
      "xcodedarkhc",
      "xcodehc",
      "xcodelight",
      "xcodelighthc",
      "xcodewwdc",
    },
  },
  xcodewwdc = {
    handle = "lunacookies/vim-colors-xcode",
    url = "https://github.com/lunacookies/vim-colors-xcode",
    github_stars = 581,
    last_git_commit = "2023-11-06",
    priority = 0,
    source = "vsc",
    git_path = "lunacookies-vim-colors-xcode",
    git_branch = nil,
    color_names = {
      "xcode",
      "xcodedark",
      "xcodedarkhc",
      "xcodehc",
      "xcodelight",
      "xcodelighthc",
      "xcodewwdc",
    },
  },
  hybrid_material = {
    handle = "kristijanhusak/vim-hybrid-material",
    url = "https://github.com/kristijanhusak/vim-hybrid-material",
    github_stars = 545,
    last_git_commit = "2020-06-16",
    priority = 0,
    source = "vsc",
    git_path = "kristijanhusak-vim-hybrid-material",
    git_branch = nil,
    color_names = {
      "hybrid_material",
      "hybrid_reverse",
    },
  },
  hybrid_reverse = {
    handle = "kristijanhusak/vim-hybrid-material",
    url = "https://github.com/kristijanhusak/vim-hybrid-material",
    github_stars = 545,
    last_git_commit = "2020-06-16",
    priority = 0,
    source = "vsc",
    git_path = "kristijanhusak-vim-hybrid-material",
    git_branch = nil,
    color_names = {
      "hybrid_material",
      "hybrid_reverse",
    },
  },
  dogrun = {
    handle = "wadackel/vim-dogrun",
    url = "https://github.com/wadackel/vim-dogrun",
    github_stars = 537,
    last_git_commit = "2024-07-24",
    priority = 0,
    source = "vsc",
    git_path = "wadackel-vim-dogrun",
    git_branch = nil,
    color_names = {
      "dogrun",
    },
  },
  gruvbox8 = {
    handle = "lifepillar/vim-gruvbox8",
    url = "https://github.com/lifepillar/vim-gruvbox8",
    github_stars = 520,
    last_git_commit = "2023-08-04",
    priority = 0,
    source = "vsc",
    git_path = "lifepillar-vim-gruvbox8",
    git_branch = "neovim",
    color_names = {
      "gruvbox8",
      "gruvbox8_hard",
      "gruvbox8_soft",
    },
  },
  gruvbox8_hard = {
    handle = "lifepillar/vim-gruvbox8",
    url = "https://github.com/lifepillar/vim-gruvbox8",
    github_stars = 520,
    last_git_commit = "2023-08-04",
    priority = 0,
    source = "vsc",
    git_path = "lifepillar-vim-gruvbox8",
    git_branch = "neovim",
    color_names = {
      "gruvbox8",
      "gruvbox8_hard",
      "gruvbox8_soft",
    },
  },
  gruvbox8_soft = {
    handle = "lifepillar/vim-gruvbox8",
    url = "https://github.com/lifepillar/vim-gruvbox8",
    github_stars = 520,
    last_git_commit = "2023-08-04",
    priority = 0,
    source = "vsc",
    git_path = "lifepillar-vim-gruvbox8",
    git_branch = "neovim",
    color_names = {
      "gruvbox8",
      "gruvbox8_hard",
      "gruvbox8_soft",
    },
  },
  rigel = {
    handle = "rigellute/rigel",
    url = "https://github.com/rigellute/rigel",
    github_stars = 512,
    last_git_commit = "2024-01-11",
    priority = 0,
    source = "vsc",
    git_path = "rigellute-rigel",
    git_branch = nil,
    color_names = {
      "rigel",
    },
  },
  spacecamp = {
    handle = "jaredgorski/spacecamp",
    url = "https://github.com/jaredgorski/spacecamp",
    github_stars = 509,
    last_git_commit = "2023-08-25",
    priority = 0,
    source = "vsc",
    git_path = "jaredgorski-spacecamp",
    git_branch = nil,
    color_names = {
      "spacecamp",
      "spacecamp_lite",
    },
  },
  spacecamp_lite = {
    handle = "jaredgorski/spacecamp",
    url = "https://github.com/jaredgorski/spacecamp",
    github_stars = 509,
    last_git_commit = "2023-08-25",
    priority = 0,
    source = "vsc",
    git_path = "jaredgorski-spacecamp",
    git_branch = nil,
    color_names = {
      "spacecamp",
      "spacecamp_lite",
    },
  },
}