return {
  ["folke/tokyonight.nvim"] = {
    handle = "folke/tokyonight.nvim",
    url = "https://github.com/folke/tokyonight.nvim",
    github_stars = 6100,
    last_git_commit = "2024-08-31",
    priority = 100,
    source = "asm",
    git_path = "folke-tokyonight.nvim",
    git_branch = nil,
    color_names = {
      "tokyonight",
      "tokyonight-day",
      "tokyonight-moon",
      "tokyonight-night",
      "tokyonight-storm",
    },
  },
  ["catppuccin/nvim"] = {
    handle = "catppuccin/nvim",
    url = "https://github.com/catppuccin/nvim",
    github_stars = 5300,
    last_git_commit = "2024-09-15",
    priority = 100,
    source = "asm",
    git_path = "catppuccin-nvim",
    git_branch = nil,
    color_names = {
      "catppuccin",
      "catppuccin-frappe",
      "catppuccin-latte",
      "catppuccin-macchiato",
      "catppuccin-mocha",
    },
  },
  ["rebelot/kanagawa.nvim"] = {
    handle = "rebelot/kanagawa.nvim",
    url = "https://github.com/rebelot/kanagawa.nvim",
    github_stars = 4100,
    last_git_commit = "2024-08-27",
    priority = 100,
    source = "asm",
    git_path = "rebelot-kanagawa.nvim",
    git_branch = nil,
    color_names = {
      "kanagawa",
      "kanagawa-dragon",
      "kanagawa-lotus",
      "kanagawa-wave",
    },
  },
  ["edeneast/nightfox.nvim"] = {
    handle = "edeneast/nightfox.nvim",
    url = "https://github.com/edeneast/nightfox.nvim",
    github_stars = 3000,
    last_git_commit = "2024-09-08",
    priority = 100,
    source = "asm",
    git_path = "edeneast-nightfox.nvim",
    git_branch = nil,
    color_names = {
      "carbonfox",
      "dawnfox",
      "dayfox",
      "duskfox",
      "nightfox",
      "nordfox",
      "terafox",
    },
  },
  ["sainnhe/everforest"] = {
    handle = "sainnhe/everforest",
    url = "https://github.com/sainnhe/everforest",
    github_stars = 2800,
    last_git_commit = "2024-09-02",
    priority = 100,
    source = "asm",
    git_path = "sainnhe-everforest",
    git_branch = nil,
    color_names = {
      "everforest",
    },
  },
  ["nlknguyen/papercolor-theme"] = {
    handle = "nlknguyen/papercolor-theme",
    url = "https://github.com/nlknguyen/papercolor-theme",
    github_stars = 2691,
    last_git_commit = "2024-03-12",
    priority = 0,
    source = "vsc",
    git_path = "nlknguyen-papercolor-theme",
    git_branch = nil,
    color_names = {
      "PaperColor",
    },
  },
  ["rose-pine/neovim"] = {
    handle = "rose-pine/neovim",
    url = "https://github.com/rose-pine/neovim",
    github_stars = 2200,
    last_git_commit = "2024-08-25",
    priority = 100,
    source = "asm",
    git_path = "rose-pine-neovim",
    git_branch = nil,
    color_names = {
      "rose-pine",
      "rose-pine-dawn",
      "rose-pine-main",
      "rose-pine-moon",
    },
  },
  ["cocopon/iceberg.vim"] = {
    handle = "cocopon/iceberg.vim",
    url = "https://github.com/cocopon/iceberg.vim",
    github_stars = 2194,
    last_git_commit = "2024-06-19",
    priority = 0,
    source = "vsc",
    git_path = "cocopon-iceberg.vim",
    git_branch = nil,
    color_names = {
      "iceberg",
    },
  },
  ["projekt0n/github-nvim-theme"] = {
    handle = "projekt0n/github-nvim-theme",
    url = "https://github.com/projekt0n/github-nvim-theme",
    github_stars = 2100,
    last_git_commit = "2024-08-11",
    priority = 100,
    source = "asm",
    git_path = "projekt0n-github-nvim-theme",
    git_branch = nil,
    color_names = {
      "github_dark",
      "github_dark_colorblind",
      "github_dark_default",
      "github_dark_dimmed",
      "github_dark_high_contrast",
      "github_dark_tritanopia",
      "github_light",
      "github_light_colorblind",
      "github_light_default",
      "github_light_high_contrast",
      "github_light_tritanopia",
    },
  },
  ["rakr/vim-one"] = {
    handle = "rakr/vim-one",
    url = "https://github.com/rakr/vim-one",
    github_stars = 1984,
    last_git_commit = "2020-12-14",
    priority = 0,
    source = "vsc",
    git_path = "rakr-vim-one",
    git_branch = nil,
    color_names = {
      "one",
    },
  },
  ["sainnhe/gruvbox-material"] = {
    handle = "sainnhe/gruvbox-material",
    url = "https://github.com/sainnhe/gruvbox-material",
    github_stars = 1900,
    last_git_commit = "2024-09-02",
    priority = 100,
    source = "asm",
    git_path = "sainnhe-gruvbox-material",
    git_branch = nil,
    color_names = {
      "gruvbox-material",
    },
  },
  ["ellisonleao/gruvbox.nvim"] = {
    handle = "ellisonleao/gruvbox.nvim",
    url = "https://github.com/ellisonleao/gruvbox.nvim",
    github_stars = 1800,
    last_git_commit = "2024-07-04",
    priority = 100,
    source = "asm",
    git_path = "ellisonleao-gruvbox.nvim",
    git_branch = nil,
    color_names = {
      "gruvbox",
    },
  },
  ["ayu-theme/ayu-vim"] = {
    handle = "ayu-theme/ayu-vim",
    url = "https://github.com/ayu-theme/ayu-vim",
    github_stars = 1672,
    last_git_commit = "2024-07-15",
    priority = 0,
    source = "vsc",
    git_path = "ayu-theme-ayu-vim",
    git_branch = nil,
    color_names = {
      "ayu",
    },
  },
  ["junegunn/seoul256.vim"] = {
    handle = "junegunn/seoul256.vim",
    url = "https://github.com/junegunn/seoul256.vim",
    github_stars = 1647,
    last_git_commit = "2023-05-03",
    priority = 0,
    source = "vsc",
    git_path = "junegunn-seoul256.vim",
    git_branch = nil,
    color_names = {
      "seoul256",
      "seoul256-light",
    },
  },
  ["sainnhe/sonokai"] = {
    handle = "sainnhe/sonokai",
    url = "https://github.com/sainnhe/sonokai",
    github_stars = 1600,
    last_git_commit = "2024-09-02",
    priority = 100,
    source = "asm",
    git_path = "sainnhe-sonokai",
    git_branch = nil,
    color_names = {
      "sonokai",
    },
  },
  ["navarasu/onedark.nvim"] = {
    handle = "navarasu/onedark.nvim",
    url = "https://github.com/navarasu/onedark.nvim",
    github_stars = 1500,
    last_git_commit = "2024-07-05",
    priority = 100,
    source = "asm",
    git_path = "navarasu-onedark.nvim",
    git_branch = nil,
    color_names = {
      "onedark",
    },
  },
  ["ku1ik/vim-monokai"] = {
    handle = "ku1ik/vim-monokai",
    url = "https://github.com/ku1ik/vim-monokai",
    github_stars = 1435,
    last_git_commit = "2022-02-09",
    priority = 0,
    source = "vsc",
    git_path = "ku1ik-vim-monokai",
    git_branch = nil,
    color_names = {
      "monokai",
    },
  },
  ["dracula/vim"] = {
    handle = "dracula/vim",
    url = "https://github.com/dracula/vim",
    github_stars = 1300,
    last_git_commit = "2024-07-21",
    priority = 100,
    source = "asm",
    git_path = "dracula-vim",
    git_branch = nil,
    color_names = {
      "dracula",
    },
  },
  ["sjl/badwolf"] = {
    handle = "sjl/badwolf",
    url = "https://github.com/sjl/badwolf",
    github_stars = 1248,
    last_git_commit = "2024-05-23",
    priority = 0,
    source = "vsc",
    git_path = "sjl-badwolf",
    git_branch = nil,
    color_names = {
      "badwolf",
      "goodwolf",
    },
  },
  ["whatyouhide/vim-gotham"] = {
    handle = "whatyouhide/vim-gotham",
    url = "https://github.com/whatyouhide/vim-gotham",
    github_stars = 1242,
    last_git_commit = "2023-01-19",
    priority = 0,
    source = "vsc",
    git_path = "whatyouhide-vim-gotham",
    git_branch = nil,
    color_names = {
      "gotham",
      "gotham256",
    },
  },
  ["jacoborus/tender.vim"] = {
    handle = "jacoborus/tender.vim",
    url = "https://github.com/jacoborus/tender.vim",
    github_stars = 1132,
    last_git_commit = "2024-09-06",
    priority = 0,
    source = "vsc",
    git_path = "jacoborus-tender.vim",
    git_branch = nil,
    color_names = {
      "tender",
    },
  },
  ["nyoom-engineering/oxocarbon.nvim"] = {
    handle = "nyoom-engineering/oxocarbon.nvim",
    url = "https://github.com/nyoom-engineering/oxocarbon.nvim",
    github_stars = 1100,
    last_git_commit = "2024-08-28",
    priority = 100,
    source = "asm",
    git_path = "nyoom-engineering-oxocarbon.nvim",
    git_branch = nil,
    color_names = {
      "oxocarbon",
    },
  },
  ["mhartington/oceanic-next"] = {
    handle = "mhartington/oceanic-next",
    url = "https://github.com/mhartington/oceanic-next",
    github_stars = 1100,
    last_git_commit = "2023-05-01",
    priority = 100,
    source = "asm",
    git_path = "mhartington-oceanic-next",
    git_branch = nil,
    color_names = {
      "OceanicNext",
      "OceanicNextLight",
    },
  },
  ["lifepillar/vim-solarized8"] = {
    handle = "lifepillar/vim-solarized8",
    url = "https://github.com/lifepillar/vim-solarized8",
    github_stars = 1007,
    last_git_commit = "2024-05-21",
    priority = 0,
    source = "vsc",
    git_path = "lifepillar-vim-solarized8",
    git_branch = "neovim",
    color_names = {
      "solarized8",
      "solarized8_flat",
      "solarized8_high",
      "solarized8_low",
    },
  },
  ["marko-cerovac/material.nvim"] = {
    handle = "marko-cerovac/material.nvim",
    url = "https://github.com/marko-cerovac/material.nvim",
    github_stars = 969,
    last_git_commit = "2024-09-03",
    priority = 100,
    source = "asm",
    git_path = "marko-cerovac-material.nvim",
    git_branch = nil,
    color_names = {
      "material",
      "material-darker",
      "material-deep-ocean",
      "material-lighter",
      "material-oceanic",
      "material-palenight",
    },
  },
  ["tomasiser/vim-code-dark"] = {
    handle = "tomasiser/vim-code-dark",
    url = "https://github.com/tomasiser/vim-code-dark",
    github_stars = 944,
    last_git_commit = "2024-05-21",
    priority = 100,
    source = "asm",
    git_path = "tomasiser-vim-code-dark",
    git_branch = nil,
    color_names = {
      "codedark",
    },
  },
  ["jnurmine/zenburn"] = {
    handle = "jnurmine/zenburn",
    url = "https://github.com/jnurmine/zenburn",
    github_stars = 892,
    last_git_commit = "2022-08-08",
    priority = 0,
    source = "vsc",
    git_path = "jnurmine-zenburn",
    git_branch = nil,
    color_names = {
      "zenburn",
    },
  },
  ["romainl/apprentice"] = {
    handle = "romainl/apprentice",
    url = "https://github.com/romainl/apprentice",
    github_stars = 884,
    last_git_commit = "2024-07-30",
    priority = 0,
    source = "vsc",
    git_path = "romainl-apprentice",
    git_branch = nil,
    color_names = {
      "apprentice",
    },
  },
  ["sainnhe/edge"] = {
    handle = "sainnhe/edge",
    url = "https://github.com/sainnhe/edge",
    github_stars = 865,
    last_git_commit = "2024-09-02",
    priority = 100,
    source = "asm",
    git_path = "sainnhe-edge",
    git_branch = nil,
    color_names = {
      "edge",
    },
  },
  ["srcery-colors/srcery-vim"] = {
    handle = "srcery-colors/srcery-vim",
    url = "https://github.com/srcery-colors/srcery-vim",
    github_stars = 818,
    last_git_commit = "2024-05-30",
    priority = 0,
    source = "vsc",
    git_path = "srcery-colors-srcery-vim",
    git_branch = nil,
    color_names = {
      "srcery",
    },
  },
  ["bluz71/vim-moonfly-colors"] = {
    handle = "bluz71/vim-moonfly-colors",
    url = "https://github.com/bluz71/vim-moonfly-colors",
    github_stars = 809,
    last_git_commit = "2024-07-25",
    priority = 100,
    source = "asm",
    git_path = "bluz71-vim-moonfly-colors",
    git_branch = nil,
    color_names = {
      "moonfly",
    },
  },
  ["pineapplegiant/spaceduck"] = {
    handle = "pineapplegiant/spaceduck",
    url = "https://github.com/pineapplegiant/spaceduck",
    github_stars = 804,
    last_git_commit = "2022-02-21",
    priority = 0,
    source = "vsc",
    git_path = "pineapplegiant-spaceduck",
    git_branch = nil,
    color_names = {
      "spaceduck",
    },
  },
  ["shaunsingh/nord.nvim"] = {
    handle = "shaunsingh/nord.nvim",
    url = "https://github.com/shaunsingh/nord.nvim",
    github_stars = 803,
    last_git_commit = "2023-12-20",
    priority = 100,
    source = "asm",
    git_path = "shaunsingh-nord.nvim",
    git_branch = nil,
    color_names = {
      "nord",
    },
  },
  ["bluz71/vim-nightfly-colors"] = {
    handle = "bluz71/vim-nightfly-colors",
    url = "https://github.com/bluz71/vim-nightfly-colors",
    github_stars = 796,
    last_git_commit = "2024-07-25",
    priority = 100,
    source = "asm",
    git_path = "bluz71-vim-nightfly-colors",
    git_branch = nil,
    color_names = {
      "nightfly",
    },
  },
  ["raphamorim/lucario"] = {
    handle = "raphamorim/lucario",
    url = "https://github.com/raphamorim/lucario",
    github_stars = 796,
    last_git_commit = "2024-06-23",
    priority = 0,
    source = "vsc",
    git_path = "raphamorim-lucario",
    git_branch = nil,
    color_names = {
      "lucario",
    },
  },
  ["ajmwagar/vim-deus"] = {
    handle = "ajmwagar/vim-deus",
    url = "https://github.com/ajmwagar/vim-deus",
    github_stars = 764,
    last_git_commit = "2021-03-28",
    priority = 0,
    source = "vsc",
    git_path = "ajmwagar-vim-deus",
    git_branch = nil,
    color_names = {
      "deus",
    },
  },
  ["fenetikm/falcon"] = {
    handle = "fenetikm/falcon",
    url = "https://github.com/fenetikm/falcon",
    github_stars = 719,
    last_git_commit = "2023-03-12",
    priority = 100,
    source = "asm",
    git_path = "fenetikm-falcon",
    git_branch = nil,
    color_names = {
      "falcon",
    },
  },
  ["savq/melange-nvim"] = {
    handle = "savq/melange-nvim",
    url = "https://github.com/savq/melange-nvim",
    github_stars = 693,
    last_git_commit = "2024-08-27",
    priority = 100,
    source = "asm",
    git_path = "savq-melange-nvim",
    git_branch = nil,
    color_names = {
      "melange",
    },
  },
  ["mofiqul/vscode.nvim"] = {
    handle = "mofiqul/vscode.nvim",
    url = "https://github.com/mofiqul/vscode.nvim",
    github_stars = 692,
    last_git_commit = "2024-08-08",
    priority = 100,
    source = "asm",
    git_path = "mofiqul-vscode.nvim",
    git_branch = nil,
    color_names = {
      "vscode",
    },
  },
  ["mcchrish/zenbones.nvim"] = {
    handle = "mcchrish/zenbones.nvim",
    url = "https://github.com/mcchrish/zenbones.nvim",
    github_stars = 685,
    last_git_commit = "2024-09-12",
    priority = 100,
    source = "asm",
    git_path = "mcchrish-zenbones.nvim",
    git_branch = nil,
    color_names = {
      "duckbones",
      "forestbones",
      "kanagawabones",
      "neobones",
      "nordbones",
      "randombones",
      "rosebones",
      "seoulbones",
      "tokyobones",
      "vimbones",
      "zenbones",
      "zenburned",
      "zenwritten",
    },
  },
  ["alexvzyl/nordic.nvim"] = {
    handle = "alexvzyl/nordic.nvim",
    url = "https://github.com/alexvzyl/nordic.nvim",
    github_stars = 678,
    last_git_commit = "2024-04-14",
    priority = 100,
    source = "asm",
    git_path = "alexvzyl-nordic.nvim",
    git_branch = nil,
    color_names = {
      "nordic",
    },
  },
  ["drewtempelmeyer/palenight.vim"] = {
    handle = "drewtempelmeyer/palenight.vim",
    url = "https://github.com/drewtempelmeyer/palenight.vim",
    github_stars = 655,
    last_git_commit = "2023-04-27",
    priority = 0,
    source = "vsc",
    git_path = "drewtempelmeyer-palenight.vim",
    git_branch = nil,
    color_names = {
      "palenight",
    },
  },
  ["craftzdog/solarized-osaka.nvim"] = {
    handle = "craftzdog/solarized-osaka.nvim",
    url = "https://github.com/craftzdog/solarized-osaka.nvim",
    github_stars = 652,
    last_git_commit = "2024-07-03",
    priority = 0,
    source = "vsc",
    git_path = "craftzdog-solarized-osaka.nvim",
    git_branch = nil,
    color_names = {
      "solarized-osaka",
      "solarized-osaka-day",
      "solarized-osaka-moon",
      "solarized-osaka-night",
      "solarized-osaka-storm",
    },
  },
  ["embark-theme/vim"] = {
    handle = "embark-theme/vim",
    url = "https://github.com/embark-theme/vim",
    github_stars = 650,
    last_git_commit = "2024-06-25",
    priority = 100,
    source = "asm",
    git_path = "embark-theme-vim",
    git_branch = nil,
    color_names = {
      "embark",
    },
  },
  ["tjdevries/colorbuddy.nvim"] = {
    handle = "tjdevries/colorbuddy.nvim",
    url = "https://github.com/tjdevries/colorbuddy.nvim",
    github_stars = 643,
    last_git_commit = "2024-05-08",
    priority = 0,
    source = "vsc",
    git_path = "tjdevries-colorbuddy.nvim",
    git_branch = nil,
    color_names = {
      "colorbuddy",
      "gruvbuddy",
    },
  },
  ["preservim/vim-colors-pencil"] = {
    handle = "preservim/vim-colors-pencil",
    url = "https://github.com/preservim/vim-colors-pencil",
    github_stars = 604,
    last_git_commit = "2022-05-07",
    priority = 0,
    source = "vsc",
    git_path = "preservim-vim-colors-pencil",
    git_branch = nil,
    color_names = {
      "pencil",
    },
  },
  ["scottmckendry/cyberdream.nvim"] = {
    handle = "scottmckendry/cyberdream.nvim",
    url = "https://github.com/scottmckendry/cyberdream.nvim",
    github_stars = 601,
    last_git_commit = "2024-09-12",
    priority = 100,
    source = "asm",
    git_path = "scottmckendry-cyberdream.nvim",
    git_branch = nil,
    color_names = {
      "cyberdream",
    },
  },
  ["liuchengxu/space-vim-dark"] = {
    handle = "liuchengxu/space-vim-dark",
    url = "https://github.com/liuchengxu/space-vim-dark",
    github_stars = 593,
    last_git_commit = "2023-11-04",
    priority = 0,
    source = "vsc",
    git_path = "liuchengxu-space-vim-dark",
    git_branch = nil,
    color_names = {
      "space-vim-dark",
    },
  },
  ["lunacookies/vim-colors-xcode"] = {
    handle = "lunacookies/vim-colors-xcode",
    url = "https://github.com/lunacookies/vim-colors-xcode",
    github_stars = 592,
    last_git_commit = "2023-11-06",
    priority = 0,
    source = "vsc",
    git_path = "lunacookies-vim-colors-xcode",
    git_branch = nil,
    color_names = {
      "xcode",
      "xcodedark",
      "xcodedarkhc",
      "xcodehc",
      "xcodelight",
      "xcodelighthc",
      "xcodewwdc",
    },
  },
  ["challenger-deep-theme/vim"] = {
    handle = "challenger-deep-theme/vim",
    url = "https://github.com/challenger-deep-theme/vim",
    github_stars = 587,
    last_git_commit = "2022-04-25",
    priority = 0,
    source = "vsc",
    git_path = "challenger-deep-theme-vim",
    git_branch = nil,
    color_names = {
      "challenger_deep",
    },
  },
  ["wadackel/vim-dogrun"] = {
    handle = "wadackel/vim-dogrun",
    url = "https://github.com/wadackel/vim-dogrun",
    github_stars = 546,
    last_git_commit = "2024-08-25",
    priority = 0,
    source = "vsc",
    git_path = "wadackel-vim-dogrun",
    git_branch = nil,
    color_names = {
      "dogrun",
    },
  },
  ["kristijanhusak/vim-hybrid-material"] = {
    handle = "kristijanhusak/vim-hybrid-material",
    url = "https://github.com/kristijanhusak/vim-hybrid-material",
    github_stars = 545,
    last_git_commit = "2020-06-16",
    priority = 0,
    source = "vsc",
    git_path = "kristijanhusak-vim-hybrid-material",
    git_branch = nil,
    color_names = {
      "hybrid_material",
      "hybrid_reverse",
    },
  },
  ["lifepillar/vim-gruvbox8"] = {
    handle = "lifepillar/vim-gruvbox8",
    url = "https://github.com/lifepillar/vim-gruvbox8",
    github_stars = 523,
    last_git_commit = "2023-08-04",
    priority = 0,
    source = "vsc",
    git_path = "lifepillar-vim-gruvbox8",
    git_branch = "neovim",
    color_names = {
      "gruvbox8",
      "gruvbox8_hard",
      "gruvbox8_soft",
    },
  },
  ["rmehri01/onenord.nvim"] = {
    handle = "rmehri01/onenord.nvim",
    url = "https://github.com/rmehri01/onenord.nvim",
    github_stars = 516,
    last_git_commit = "2024-08-22",
    priority = 100,
    source = "asm",
    git_path = "rmehri01-onenord.nvim",
    git_branch = nil,
    color_names = {
      "onenord",
      "onenord-light",
    },
  },
  ["rigellute/rigel"] = {
    handle = "rigellute/rigel",
    url = "https://github.com/rigellute/rigel",
    github_stars = 512,
    last_git_commit = "2024-01-11",
    priority = 0,
    source = "vsc",
    git_path = "rigellute-rigel",
    git_branch = nil,
    color_names = {
      "rigel",
    },
  },
  ["jaredgorski/spacecamp"] = {
    handle = "jaredgorski/spacecamp",
    url = "https://github.com/jaredgorski/spacecamp",
    github_stars = 510,
    last_git_commit = "2023-08-25",
    priority = 0,
    source = "vsc",
    git_path = "jaredgorski-spacecamp",
    git_branch = nil,
    color_names = {
      "spacecamp",
      "spacecamp_lite",
    },
  },
}