name: Collector
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  pipeline:
    name: Pipeline
    if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: Homebrew/actions/setup-homebrew@main
      - uses: browser-actions/setup-chrome@v2
        with:
          install-chromedriver: true
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Collect Colors
        run: |
          python3 -m venv venv
          . venv/bin/activate
          python3 -m pip install -r requirements.txt
          python3 collect.py
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(colors): auto update colorschemes ${{ env.COLLECT_CHANGE }}"
          push_options: "--force"
          file_pattern: "db.json COLORSCHEMES.md collect.py.log lua/colorbox/meta/*.lua"
