return {
  ["folke/tokyonight.nvim"] = {
    handle = "folke/tokyonight.nvim",
    url = "https://github.com/folke/tokyonight.nvim",
    github_stars = 4900,
    last_git_commit = "2024-03-28",
    priority = 100,
    source = "asm",
    git_path = "folke-tokyonight.nvim",
    git_branch = nil,
    color_names = {
      "tokyonight",
      "tokyonight-day",
      "tokyonight-moon",
      "tokyonight-night",
      "tokyonight-storm",
    },
  },
  ["catppuccin/nvim"] = {
    handle = "catppuccin/nvim",
    url = "https://github.com/catppuccin/nvim",
    github_stars = 4300,
    last_git_commit = "2024-03-29",
    priority = 100,
    source = "asm",
    git_path = "catppuccin-nvim",
    git_branch = nil,
    color_names = {
      "catppuccin",
      "catppuccin-frappe",
      "catppuccin-latte",
      "catppuccin-macchiato",
      "catppuccin-mocha",
    },
  },
  ["rebelot/kanagawa.nvim"] = {
    handle = "rebelot/kanagawa.nvim",
    url = "https://github.com/rebelot/kanagawa.nvim",
    github_stars = 3300,
    last_git_commit = "2024-02-28",
    priority = 100,
    source = "asm",
    git_path = "rebelot-kanagawa.nvim",
    git_branch = nil,
    color_names = {
      "kanagawa",
      "kanagawa-dragon",
      "kanagawa-lotus",
      "kanagawa-wave",
    },
  },
  ["nlknguyen/papercolor-theme"] = {
    handle = "nlknguyen/papercolor-theme",
    url = "https://github.com/nlknguyen/papercolor-theme",
    github_stars = 2610,
    last_git_commit = "2024-03-12",
    priority = 0,
    source = "vsc",
    git_path = "nlknguyen-papercolor-theme",
    git_branch = nil,
    color_names = {
      "PaperColor",
    },
  },
  ["edeneast/nightfox.nvim"] = {
    handle = "edeneast/nightfox.nvim",
    url = "https://github.com/edeneast/nightfox.nvim",
    github_stars = 2600,
    last_git_commit = "2024-03-18",
    priority = 100,
    source = "asm",
    git_path = "edeneast-nightfox.nvim",
    git_branch = nil,
    color_names = {
      "carbonfox",
      "dawnfox",
      "dayfox",
      "duskfox",
      "nightfox",
      "nordfox",
      "terafox",
    },
  },
  ["sainnhe/everforest"] = {
    handle = "sainnhe/everforest",
    url = "https://github.com/sainnhe/everforest",
    github_stars = 2400,
    last_git_commit = "2024-03-27",
    priority = 100,
    source = "asm",
    git_path = "sainnhe-everforest",
    git_branch = nil,
    color_names = {
      "everforest",
    },
  },
  ["cocopon/iceberg.vim"] = {
    handle = "cocopon/iceberg.vim",
    url = "https://github.com/cocopon/iceberg.vim",
    github_stars = 2127,
    last_git_commit = "2022-11-23",
    priority = 0,
    source = "vsc",
    git_path = "cocopon-iceberg.vim",
    git_branch = nil,
    color_names = {
      "iceberg",
    },
  },
  ["rakr/vim-one"] = {
    handle = "rakr/vim-one",
    url = "https://github.com/rakr/vim-one",
    github_stars = 1977,
    last_git_commit = "2020-12-14",
    priority = 0,
    source = "vsc",
    git_path = "rakr-vim-one",
    git_branch = nil,
    color_names = {
      "one",
    },
  },
  ["projekt0n/github-nvim-theme"] = {
    handle = "projekt0n/github-nvim-theme",
    url = "https://github.com/projekt0n/github-nvim-theme",
    github_stars = 1900,
    last_git_commit = "2024-01-31",
    priority = 100,
    source = "asm",
    git_path = "projekt0n-github-nvim-theme",
    git_branch = nil,
    color_names = {
      "github_dark",
      "github_dark_colorblind",
      "github_dark_default",
      "github_dark_dimmed",
      "github_dark_high_contrast",
      "github_dark_tritanopia",
      "github_dimmed",
      "github_light",
      "github_light_colorblind",
      "github_light_default",
      "github_light_high_contrast",
      "github_light_tritanopia",
    },
  },
  ["rose-pine/neovim"] = {
    handle = "rose-pine/neovim",
    url = "https://github.com/rose-pine/neovim",
    github_stars = 1800,
    last_git_commit = "2024-03-30",
    priority = 100,
    source = "asm",
    git_path = "rose-pine-neovim",
    git_branch = nil,
    color_names = {
      "rose-pine",
      "rose-pine-dawn",
      "rose-pine-main",
      "rose-pine-moon",
    },
  },
  ["nanotech/jellybeans.vim"] = {
    handle = "nanotech/jellybeans.vim",
    url = "https://github.com/nanotech/jellybeans.vim",
    github_stars = 1759,
    last_git_commit = "2019-06-21",
    priority = 0,
    source = "vsc",
    git_path = "nanotech-jellybeans.vim",
    git_branch = nil,
    color_names = {
      "jellybeans",
    },
  },
  ["junegunn/seoul256.vim"] = {
    handle = "junegunn/seoul256.vim",
    url = "https://github.com/junegunn/seoul256.vim",
    github_stars = 1624,
    last_git_commit = "2023-05-03",
    priority = 0,
    source = "vsc",
    git_path = "junegunn-seoul256.vim",
    git_branch = nil,
    color_names = {
      "seoul256",
      "seoul256-light",
    },
  },
  ["ayu-theme/ayu-vim"] = {
    handle = "ayu-theme/ayu-vim",
    url = "https://github.com/ayu-theme/ayu-vim",
    github_stars = 1618,
    last_git_commit = "2020-05-29",
    priority = 0,
    source = "vsc",
    git_path = "ayu-theme-ayu-vim",
    git_branch = nil,
    color_names = {
      "ayu",
    },
  },
  ["sainnhe/gruvbox-material"] = {
    handle = "sainnhe/gruvbox-material",
    url = "https://github.com/sainnhe/gruvbox-material",
    github_stars = 1600,
    last_git_commit = "2024-03-27",
    priority = 100,
    source = "asm",
    git_path = "sainnhe-gruvbox-material",
    git_branch = nil,
    color_names = {
      "gruvbox-material",
    },
  },
  ["sainnhe/sonokai"] = {
    handle = "sainnhe/sonokai",
    url = "https://github.com/sainnhe/sonokai",
    github_stars = 1500,
    last_git_commit = "2024-03-27",
    priority = 100,
    source = "asm",
    git_path = "sainnhe-sonokai",
    git_branch = nil,
    color_names = {
      "sonokai",
    },
  },
  ["ellisonleao/gruvbox.nvim"] = {
    handle = "ellisonleao/gruvbox.nvim",
    url = "https://github.com/ellisonleao/gruvbox.nvim",
    github_stars = 1500,
    last_git_commit = "2024-01-29",
    priority = 100,
    source = "asm",
    git_path = "ellisonleao-gruvbox.nvim",
    git_branch = nil,
    color_names = {
      "gruvbox",
    },
  },
  ["ku1ik/vim-monokai"] = {
    handle = "ku1ik/vim-monokai",
    url = "https://github.com/ku1ik/vim-monokai",
    github_stars = 1420,
    last_git_commit = "2022-02-09",
    priority = 0,
    source = "vsc",
    git_path = "ku1ik-vim-monokai",
    git_branch = nil,
    color_names = {
      "monokai",
    },
  },
  ["navarasu/onedark.nvim"] = {
    handle = "navarasu/onedark.nvim",
    url = "https://github.com/navarasu/onedark.nvim",
    github_stars = 1300,
    last_git_commit = "2024-01-29",
    priority = 100,
    source = "asm",
    git_path = "navarasu-onedark.nvim",
    git_branch = nil,
    color_names = {
      "onedark",
    },
  },
  ["dracula/vim"] = {
    handle = "dracula/vim",
    url = "https://github.com/dracula/vim",
    github_stars = 1300,
    last_git_commit = "2024-01-29",
    priority = 100,
    source = "asm",
    git_path = "dracula-vim",
    git_branch = nil,
    color_names = {
      "dracula",
    },
  },
  ["sjl/badwolf"] = {
    handle = "sjl/badwolf",
    url = "https://github.com/sjl/badwolf",
    github_stars = 1238,
    last_git_commit = "2024-03-15",
    priority = 0,
    source = "vsc",
    git_path = "sjl-badwolf",
    git_branch = nil,
    color_names = {
      "badwolf",
      "goodwolf",
    },
  },
  ["whatyouhide/vim-gotham"] = {
    handle = "whatyouhide/vim-gotham",
    url = "https://github.com/whatyouhide/vim-gotham",
    github_stars = 1213,
    last_git_commit = "2023-01-19",
    priority = 0,
    source = "vsc",
    git_path = "whatyouhide-vim-gotham",
    git_branch = nil,
    color_names = {
      "gotham",
      "gotham256",
    },
  },
  ["jacoborus/tender.vim"] = {
    handle = "jacoborus/tender.vim",
    url = "https://github.com/jacoborus/tender.vim",
    github_stars = 1101,
    last_git_commit = "2024-03-21",
    priority = 0,
    source = "vsc",
    git_path = "jacoborus-tender.vim",
    git_branch = nil,
    color_names = {
      "tender",
    },
  },
  ["mhartington/oceanic-next"] = {
    handle = "mhartington/oceanic-next",
    url = "https://github.com/mhartington/oceanic-next",
    github_stars = 1100,
    last_git_commit = "2023-05-01",
    priority = 100,
    source = "asm",
    git_path = "mhartington-oceanic-next",
    git_branch = nil,
    color_names = {
      "OceanicNext",
      "OceanicNextLight",
    },
  },
  ["lifepillar/vim-solarized8"] = {
    handle = "lifepillar/vim-solarized8",
    url = "https://github.com/lifepillar/vim-solarized8",
    github_stars = 969,
    last_git_commit = "2024-01-22",
    priority = 0,
    source = "vsc",
    git_path = "lifepillar-vim-solarized8",
    git_branch = "neovim",
    color_names = {
      "solarized8",
      "solarized8_flat",
      "solarized8_high",
      "solarized8_low",
    },
  },
  ["tomasiser/vim-code-dark"] = {
    handle = "tomasiser/vim-code-dark",
    url = "https://github.com/tomasiser/vim-code-dark",
    github_stars = 898,
    last_git_commit = "2023-11-11",
    priority = 100,
    source = "asm",
    git_path = "tomasiser-vim-code-dark",
    git_branch = nil,
    color_names = {
      "codedark",
    },
  },
  ["nyoom-engineering/oxocarbon.nvim"] = {
    handle = "nyoom-engineering/oxocarbon.nvim",
    url = "https://github.com/nyoom-engineering/oxocarbon.nvim",
    github_stars = 894,
    last_git_commit = "2023-11-27",
    priority = 100,
    source = "asm",
    git_path = "nyoom-engineering-oxocarbon.nvim",
    git_branch = nil,
    color_names = {
      "oxocarbon",
    },
  },
  ["marko-cerovac/material.nvim"] = {
    handle = "marko-cerovac/material.nvim",
    url = "https://github.com/marko-cerovac/material.nvim",
    github_stars = 883,
    last_git_commit = "2024-03-27",
    priority = 100,
    source = "asm",
    git_path = "marko-cerovac-material.nvim",
    git_branch = nil,
    color_names = {
      "material",
      "material-darker",
      "material-deep-ocean",
      "material-lighter",
      "material-oceanic",
      "material-palenight",
    },
  },
  ["jnurmine/zenburn"] = {
    handle = "jnurmine/zenburn",
    url = "https://github.com/jnurmine/zenburn",
    github_stars = 874,
    last_git_commit = "2022-08-08",
    priority = 0,
    source = "vsc",
    git_path = "jnurmine-zenburn",
    git_branch = nil,
    color_names = {
      "zenburn",
    },
  },
  ["romainl/apprentice"] = {
    handle = "romainl/apprentice",
    url = "https://github.com/romainl/apprentice",
    github_stars = 867,
    last_git_commit = "2023-02-15",
    priority = 0,
    source = "vsc",
    git_path = "romainl-apprentice",
    git_branch = nil,
    color_names = {
      "apprentice",
    },
  },
  ["sainnhe/edge"] = {
    handle = "sainnhe/edge",
    url = "https://github.com/sainnhe/edge",
    github_stars = 820,
    last_git_commit = "2024-03-27",
    priority = 100,
    source = "asm",
    git_path = "sainnhe-edge",
    git_branch = nil,
    color_names = {
      "edge",
    },
  },
  ["srcery-colors/srcery-vim"] = {
    handle = "srcery-colors/srcery-vim",
    url = "https://github.com/srcery-colors/srcery-vim",
    github_stars = 790,
    last_git_commit = "2024-03-26",
    priority = 0,
    source = "vsc",
    git_path = "srcery-colors-srcery-vim",
    git_branch = nil,
    color_names = {
      "srcery",
    },
  },
  ["raphamorim/lucario"] = {
    handle = "raphamorim/lucario",
    url = "https://github.com/raphamorim/lucario",
    github_stars = 787,
    last_git_commit = "2024-01-02",
    priority = 0,
    source = "vsc",
    git_path = "raphamorim-lucario",
    git_branch = nil,
    color_names = {
      "lucario",
    },
  },
  ["pineapplegiant/spaceduck"] = {
    handle = "pineapplegiant/spaceduck",
    url = "https://github.com/pineapplegiant/spaceduck",
    github_stars = 775,
    last_git_commit = "2022-02-21",
    priority = 0,
    source = "vsc",
    git_path = "pineapplegiant-spaceduck",
    git_branch = nil,
    color_names = {
      "spaceduck",
    },
  },
  ["bluz71/vim-nightfly-colors"] = {
    handle = "bluz71/vim-nightfly-colors",
    url = "https://github.com/bluz71/vim-nightfly-colors",
    github_stars = 747,
    last_git_commit = "2024-03-28",
    priority = 100,
    source = "asm",
    git_path = "bluz71-vim-nightfly-colors",
    git_branch = nil,
    color_names = {
      "nightfly",
    },
  },
  ["ajmwagar/vim-deus"] = {
    handle = "ajmwagar/vim-deus",
    url = "https://github.com/ajmwagar/vim-deus",
    github_stars = 738,
    last_git_commit = "2021-03-28",
    priority = 0,
    source = "vsc",
    git_path = "ajmwagar-vim-deus",
    git_branch = nil,
    color_names = {
      "deus",
    },
  },
  ["shaunsingh/nord.nvim"] = {
    handle = "shaunsingh/nord.nvim",
    url = "https://github.com/shaunsingh/nord.nvim",
    github_stars = 732,
    last_git_commit = "2023-12-20",
    priority = 100,
    source = "asm",
    git_path = "shaunsingh-nord.nvim",
    git_branch = nil,
    color_names = {
      "nord",
    },
  },
  ["bluz71/vim-moonfly-colors"] = {
    handle = "bluz71/vim-moonfly-colors",
    url = "https://github.com/bluz71/vim-moonfly-colors",
    github_stars = 717,
    last_git_commit = "2024-03-28",
    priority = 100,
    source = "asm",
    git_path = "bluz71-vim-moonfly-colors",
    git_branch = nil,
    color_names = {
      "moonfly",
    },
  },
  ["fenetikm/falcon"] = {
    handle = "fenetikm/falcon",
    url = "https://github.com/fenetikm/falcon",
    github_stars = 692,
    last_git_commit = "2023-03-12",
    priority = 100,
    source = "asm",
    git_path = "fenetikm-falcon",
    git_branch = nil,
    color_names = {
      "falcon",
    },
  },
  ["drewtempelmeyer/palenight.vim"] = {
    handle = "drewtempelmeyer/palenight.vim",
    url = "https://github.com/drewtempelmeyer/palenight.vim",
    github_stars = 649,
    last_git_commit = "2023-04-27",
    priority = 0,
    source = "vsc",
    git_path = "drewtempelmeyer-palenight.vim",
    git_branch = nil,
    color_names = {
      "palenight",
    },
  },
  ["embark-theme/vim"] = {
    handle = "embark-theme/vim",
    url = "https://github.com/embark-theme/vim",
    github_stars = 617,
    last_git_commit = "2024-02-14",
    priority = 100,
    source = "asm",
    git_path = "embark-theme-vim",
    git_branch = nil,
    color_names = {
      "embark",
    },
  },
  ["preservim/vim-colors-pencil"] = {
    handle = "preservim/vim-colors-pencil",
    url = "https://github.com/preservim/vim-colors-pencil",
    github_stars = 597,
    last_git_commit = "2022-05-07",
    priority = 0,
    source = "vsc",
    git_path = "preservim-vim-colors-pencil",
    git_branch = nil,
    color_names = {
      "pencil",
    },
  },
  ["savq/melange-nvim"] = {
    handle = "savq/melange-nvim",
    url = "https://github.com/savq/melange-nvim",
    github_stars = 588,
    last_git_commit = "2024-02-16",
    priority = 100,
    source = "asm",
    git_path = "savq-melange-nvim",
    git_branch = nil,
    color_names = {
      "melange",
    },
  },
  ["mofiqul/vscode.nvim"] = {
    handle = "mofiqul/vscode.nvim",
    url = "https://github.com/mofiqul/vscode.nvim",
    github_stars = 586,
    last_git_commit = "2024-03-24",
    priority = 100,
    source = "asm",
    git_path = "mofiqul-vscode.nvim",
    git_branch = nil,
    color_names = {
      "vscode",
    },
  },
  ["tjdevries/colorbuddy.nvim"] = {
    handle = "tjdevries/colorbuddy.nvim",
    url = "https://github.com/tjdevries/colorbuddy.nvim",
    github_stars = 582,
    last_git_commit = "2024-03-20",
    priority = 0,
    source = "vsc",
    git_path = "tjdevries-colorbuddy.nvim",
    git_branch = nil,
    color_names = {
      "colorbuddy",
      "gruvbuddy",
    },
  },
  ["challenger-deep-theme/vim"] = {
    handle = "challenger-deep-theme/vim",
    url = "https://github.com/challenger-deep-theme/vim",
    github_stars = 581,
    last_git_commit = "2022-04-25",
    priority = 0,
    source = "vsc",
    git_path = "challenger-deep-theme-vim",
    git_branch = nil,
    color_names = {
      "challenger_deep",
    },
  },
  ["liuchengxu/space-vim-dark"] = {
    handle = "liuchengxu/space-vim-dark",
    url = "https://github.com/liuchengxu/space-vim-dark",
    github_stars = 573,
    last_git_commit = "2023-11-04",
    priority = 0,
    source = "vsc",
    git_path = "liuchengxu-space-vim-dark",
    git_branch = nil,
    color_names = {
      "space-vim-dark",
    },
  },
  ["mcchrish/zenbones.nvim"] = {
    handle = "mcchrish/zenbones.nvim",
    url = "https://github.com/mcchrish/zenbones.nvim",
    github_stars = 558,
    last_git_commit = "2024-03-30",
    priority = 100,
    source = "asm",
    git_path = "mcchrish-zenbones.nvim",
    git_branch = nil,
    color_names = {
      "duckbones",
      "forestbones",
      "kanagawabones",
      "neobones",
      "nordbones",
      "randombones",
      "rosebones",
      "seoulbones",
      "tokyobones",
      "vimbones",
      "zenbones",
      "zenburned",
      "zenwritten",
    },
  },
  ["lunacookies/vim-colors-xcode"] = {
    handle = "lunacookies/vim-colors-xcode",
    url = "https://github.com/lunacookies/vim-colors-xcode",
    github_stars = 551,
    last_git_commit = "2023-11-06",
    priority = 0,
    source = "vsc",
    git_path = "lunacookies-vim-colors-xcode",
    git_branch = nil,
    color_names = {
      "xcode",
      "xcodedark",
      "xcodedarkhc",
      "xcodehc",
      "xcodelight",
      "xcodelighthc",
      "xcodewwdc",
    },
  },
  ["kristijanhusak/vim-hybrid-material"] = {
    handle = "kristijanhusak/vim-hybrid-material",
    url = "https://github.com/kristijanhusak/vim-hybrid-material",
    github_stars = 544,
    last_git_commit = "2020-06-16",
    priority = 0,
    source = "vsc",
    git_path = "kristijanhusak-vim-hybrid-material",
    git_branch = nil,
    color_names = {
      "hybrid_material",
      "hybrid_reverse",
    },
  },
  ["alexvzyl/nordic.nvim"] = {
    handle = "alexvzyl/nordic.nvim",
    url = "https://github.com/alexvzyl/nordic.nvim",
    github_stars = 525,
    last_git_commit = "2024-03-23",
    priority = 100,
    source = "asm",
    git_path = "alexvzyl-nordic.nvim",
    git_branch = nil,
    color_names = {
      "nordic",
    },
  },
  ["wadackel/vim-dogrun"] = {
    handle = "wadackel/vim-dogrun",
    url = "https://github.com/wadackel/vim-dogrun",
    github_stars = 511,
    last_git_commit = "2024-02-20",
    priority = 0,
    source = "vsc",
    git_path = "wadackel-vim-dogrun",
    git_branch = nil,
    color_names = {
      "dogrun",
    },
  },
  ["rigellute/rigel"] = {
    handle = "rigellute/rigel",
    url = "https://github.com/rigellute/rigel",
    github_stars = 508,
    last_git_commit = "2024-01-11",
    priority = 0,
    source = "vsc",
    git_path = "rigellute-rigel",
    git_branch = nil,
    color_names = {
      "rigel",
    },
  },
  ["lifepillar/vim-gruvbox8"] = {
    handle = "lifepillar/vim-gruvbox8",
    url = "https://github.com/lifepillar/vim-gruvbox8",
    github_stars = 501,
    last_git_commit = "2023-08-04",
    priority = 0,
    source = "vsc",
    git_path = "lifepillar-vim-gruvbox8",
    git_branch = "neovim",
    color_names = {
      "gruvbox8",
      "gruvbox8_hard",
      "gruvbox8_soft",
    },
  },
}