return {
  ["folke/tokyonight.nvim"] = {
    h = "folke/tokyonight.nvim",
    st = 4900,
    gc = "2024-03-28",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["catppuccin/nvim"] = {
    h = "catppuccin/nvim",
    st = 4300,
    gc = "2024-03-29",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["rebelot/kanagawa.nvim"] = {
    h = "rebelot/kanagawa.nvim",
    st = 3300,
    gc = "2024-02-28",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["nlknguyen/papercolor-theme"] = {
    h = "nlknguyen/papercolor-theme",
    st = 2610,
    gc = "2024-03-12",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["edeneast/nightfox.nvim"] = {
    h = "edeneast/nightfox.nvim",
    st = 2600,
    gc = "2024-03-18",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["sainnhe/everforest"] = {
    h = "sainnhe/everforest",
    st = 2400,
    gc = "2024-03-27",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["cocopon/iceberg.vim"] = {
    h = "cocopon/iceberg.vim",
    st = 2127,
    gc = "2022-11-23",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["rakr/vim-one"] = {
    h = "rakr/vim-one",
    st = 1977,
    gc = "2020-12-14",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["projekt0n/github-nvim-theme"] = {
    h = "projekt0n/github-nvim-theme",
    st = 1900,
    gc = "2024-01-31",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["rose-pine/neovim"] = {
    h = "rose-pine/neovim",
    st = 1800,
    gc = "2024-03-30",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["nanotech/jellybeans.vim"] = {
    h = "nanotech/jellybeans.vim",
    st = 1759,
    gc = "2019-06-21",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["junegunn/seoul256.vim"] = {
    h = "junegunn/seoul256.vim",
    st = 1624,
    gc = "2023-05-03",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["ayu-theme/ayu-vim"] = {
    h = "ayu-theme/ayu-vim",
    st = 1618,
    gc = "2020-05-29",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["sainnhe/gruvbox-material"] = {
    h = "sainnhe/gruvbox-material",
    st = 1600,
    gc = "2024-03-27",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["sainnhe/sonokai"] = {
    h = "sainnhe/sonokai",
    st = 1500,
    gc = "2024-03-27",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["ellisonleao/gruvbox.nvim"] = {
    h = "ellisonleao/gruvbox.nvim",
    st = 1500,
    gc = "2024-01-29",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["ku1ik/vim-monokai"] = {
    h = "ku1ik/vim-monokai",
    st = 1420,
    gc = "2022-02-09",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["navarasu/onedark.nvim"] = {
    h = "navarasu/onedark.nvim",
    st = 1300,
    gc = "2024-01-29",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["dracula/vim"] = {
    h = "dracula/vim",
    st = 1300,
    gc = "2024-01-29",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["sjl/badwolf"] = {
    h = "sjl/badwolf",
    st = 1238,
    gc = "2024-03-15",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["whatyouhide/vim-gotham"] = {
    h = "whatyouhide/vim-gotham",
    st = 1213,
    gc = "2023-01-19",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["jacoborus/tender.vim"] = {
    h = "jacoborus/tender.vim",
    st = 1101,
    gc = "2024-03-21",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["mhartington/oceanic-next"] = {
    h = "mhartington/oceanic-next",
    st = 1100,
    gc = "2023-05-01",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["lifepillar/vim-solarized8"] = {
    h = "lifepillar/vim-solarized8",
    st = 969,
    gc = "2024-01-22",
    p = 0,
    s = "vsc",
    gb = "neovim",
    cn = {},
  },
  ["tomasiser/vim-code-dark"] = {
    h = "tomasiser/vim-code-dark",
    st = 898,
    gc = "2023-11-11",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["nyoom-engineering/oxocarbon.nvim"] = {
    h = "nyoom-engineering/oxocarbon.nvim",
    st = 894,
    gc = "2023-11-27",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["marko-cerovac/material.nvim"] = {
    h = "marko-cerovac/material.nvim",
    st = 883,
    gc = "2024-03-27",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["jnurmine/zenburn"] = {
    h = "jnurmine/zenburn",
    st = 874,
    gc = "2022-08-08",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["romainl/apprentice"] = {
    h = "romainl/apprentice",
    st = 867,
    gc = "2023-02-15",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["sainnhe/edge"] = {
    h = "sainnhe/edge",
    st = 820,
    gc = "2024-03-27",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["srcery-colors/srcery-vim"] = {
    h = "srcery-colors/srcery-vim",
    st = 790,
    gc = "2024-03-26",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["raphamorim/lucario"] = {
    h = "raphamorim/lucario",
    st = 787,
    gc = "2024-01-02",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["pineapplegiant/spaceduck"] = {
    h = "pineapplegiant/spaceduck",
    st = 775,
    gc = "2022-02-21",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["bluz71/vim-nightfly-colors"] = {
    h = "bluz71/vim-nightfly-colors",
    st = 747,
    gc = "2024-03-28",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["ajmwagar/vim-deus"] = {
    h = "ajmwagar/vim-deus",
    st = 738,
    gc = "2021-03-28",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["shaunsingh/nord.nvim"] = {
    h = "shaunsingh/nord.nvim",
    st = 732,
    gc = "2023-12-20",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["bluz71/vim-moonfly-colors"] = {
    h = "bluz71/vim-moonfly-colors",
    st = 717,
    gc = "2024-03-28",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["fenetikm/falcon"] = {
    h = "fenetikm/falcon",
    st = 692,
    gc = "2023-03-12",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["drewtempelmeyer/palenight.vim"] = {
    h = "drewtempelmeyer/palenight.vim",
    st = 649,
    gc = "2023-04-27",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["embark-theme/vim"] = {
    h = "embark-theme/vim",
    st = 617,
    gc = "2024-02-14",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["preservim/vim-colors-pencil"] = {
    h = "preservim/vim-colors-pencil",
    st = 597,
    gc = "2022-05-07",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["savq/melange-nvim"] = {
    h = "savq/melange-nvim",
    st = 588,
    gc = "2024-02-16",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["mofiqul/vscode.nvim"] = {
    h = "mofiqul/vscode.nvim",
    st = 586,
    gc = "2024-03-24",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["tjdevries/colorbuddy.nvim"] = {
    h = "tjdevries/colorbuddy.nvim",
    st = 582,
    gc = "2024-03-20",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["challenger-deep-theme/vim"] = {
    h = "challenger-deep-theme/vim",
    st = 581,
    gc = "2022-04-25",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["liuchengxu/space-vim-dark"] = {
    h = "liuchengxu/space-vim-dark",
    st = 573,
    gc = "2023-11-04",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["mcchrish/zenbones.nvim"] = {
    h = "mcchrish/zenbones.nvim",
    st = 558,
    gc = "2024-03-30",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["lunacookies/vim-colors-xcode"] = {
    h = "lunacookies/vim-colors-xcode",
    st = 551,
    gc = "2023-11-06",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["kristijanhusak/vim-hybrid-material"] = {
    h = "kristijanhusak/vim-hybrid-material",
    st = 544,
    gc = "2020-06-16",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["alexvzyl/nordic.nvim"] = {
    h = "alexvzyl/nordic.nvim",
    st = 525,
    gc = "2024-03-23",
    p = 100,
    s = "asm",
    gb = nil,
    cn = {},
  },
  ["wadackel/vim-dogrun"] = {
    h = "wadackel/vim-dogrun",
    st = 511,
    gc = "2024-02-20",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["rigellute/rigel"] = {
    h = "rigellute/rigel",
    st = 508,
    gc = "2024-01-11",
    p = 0,
    s = "vsc",
    gb = nil,
    cn = {},
  },
  ["lifepillar/vim-gruvbox8"] = {
    h = "lifepillar/vim-gruvbox8",
    st = 501,
    gc = "2023-08-04",
    p = 0,
    s = "vsc",
    gb = "neovim",
    cn = {},
  },
}
